/**
 * Few-shot exemplars — well-designed parametric build123d parts the harness
 * shows the model as style references. Exemplars teach *taste* (fillet
 * discipline, parametric structure, edge treatment) more effectively than any
 * rule list.
 *
 * All code here is authored in-house (fully license-clean — no third-party
 * source). Apache-2.0 build123d/bd_warehouse examples may be added later with
 * a NOTICE; marketplace meshes are NOT usable (NC/SA + wrong representation).
 *
 * VERIFICATION CONTRACT: an exemplar is only injected into a real prompt when
 * `verified: true`. These ship `verified: false` until each has been run
 * through the CAD sidecar and confirmed to compile + produce a valid
 * watertight solid (see scripts/verify-exemplars.ts). This guarantees we never
 * teach the model from code we haven't proven correct.
 */

import { FARMED_EXEMPLARS } from "./exemplars-farmed";
import type { CadEngineId } from "../engines/types";
import { selectSystemPromptSections } from "../prompt";

export interface CadExemplar {
  id: string;
  title: string;
  /** Prompt keywords this exemplar is a good match for. */
  keywords: string[];
  /** The aesthetic/structural lesson it demonstrates (kept with the few-shot). */
  lesson: string;
  /** Idiomatic build123d source. Must assign the solid to `result`. */
  code: string;
  /** Flipped to true only after the sidecar confirms it compiles + is valid. */
  verified: boolean;
}

const AUTHORED_EXEMPLARS: CadExemplar[] = [
  {
    id: "rounded_enclosure",
    title: "Rounded shelled enclosure",
    keywords: ["enclosure", "box", "case", "housing", "container", "lid", "project box"],
    lesson:
      "One reused corner radius on all vertical edges, a small consistent top-edge break, a base chamfer for stance, and a shelled interior — parametric throughout.",
    code: [
      "from build123d import *",
      "",
      "length, width, height = 80, 60, 28",
      "wall = 2.0",
      "corner_radius = 6.0   # one radius family, reused",
      "edge_break = 0.8      # small rim break, applied AFTER the shell",
      "base_chamfer = 1.0    # stance + avoids elephant-foot",
      "",
      "with BuildPart() as part:",
      "    Box(length, width, height)",
      "    fillet(part.edges().filter_by(Axis.Z), corner_radius)",
      "    chamfer(part.edges().group_by(Axis.Z)[0], base_chamfer)",
      "    top = part.faces().sort_by(Axis.Z)[-1]",
      "    offset(amount=-wall, openings=top)",
      "    # Rim break AFTER the shell: filleting the rim first and shelling",
      "    # through it leaves a sliver face the kernel cannot triangulate.",
      "    fillet(part.edges().group_by(Axis.Z)[-1], edge_break)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "fillet_hierarchy_bracket",
    title: "L-bracket with fillet hierarchy",
    keywords: ["bracket", "mount", "angle", "gusset", "support", "l-bracket"],
    lesson:
      "Fillet hierarchy: a large radius at the structural root (load path + looks), small breaks on cosmetic edges; bolt holes sized to a standard clearance.",
    code: [
      "from build123d import *",
      "",
      "arm = 40        # length of each arm",
      "width = 30",
      "thick = 5",
      "root_fillet = 3.0   # large radius where arms meet (< thickness)",
      "edge_break = 1.0",
      "hole_d = 5.5        # M5 clearance",
      "",
      "with BuildPart() as part:",
      "    Box(arm, width, thick, align=(Align.MIN, Align.CENTER, Align.MIN))",
      "    Box(thick, width, arm, align=(Align.MIN, Align.CENTER, Align.MIN))",
      "    fillet(part.edges().filter_by(Axis.Y).group_by(Axis.X)[0].sort_by(Axis.Z)[1], root_fillet)",
      "    # bolt holes through each arm",
      "    with Locations((arm - 10, 0, 0)):",
      "        Hole(hole_d / 2, depth=thick)",
      "    fillet(part.edges().filter_by(GeomType.LINE).group_by(SortBy.LENGTH)[0], edge_break)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "snap_fit_lid",
    title: "Snap-fit lid",
    keywords: ["lid", "cap", "cover", "snap", "snap-fit", "clip", "closure"],
    lesson:
      "Functional feature design: a lip with lead-in chamfer and defined clearance to the body, rounded outer edges, parametric fit gap.",
    code: [
      "from build123d import *",
      "",
      "outer = 60          # lid outer size",
      "height = 8",
      "wall = 2.0",
      "lip_h = 4.0",
      "fit_gap = 0.2       # clearance to the box inner wall (printed snug fit)",
      "edge_round = 2.0",
      "",
      "with BuildPart() as part:",
      "    Box(outer, outer, height)",
      "    fillet(part.edges().filter_by(Axis.Z), edge_round)",
      "    fillet(part.edges().group_by(Axis.Z)[-1], 1.0)",
      "    # inner lip that drops into the box",
      "    inner = outer - 2 * wall - 2 * fit_gap",
      "    with BuildSketch(part.faces().sort_by(Axis.Z)[0]):",
      "        Rectangle(inner, inner)",
      "        Rectangle(inner - 2 * wall, inner - 2 * wall, mode=Mode.SUBTRACT)",
      "    extrude(amount=lip_h)",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 0.8)  # lead-in",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "ergonomic_knob",
    title: "Ergonomic knurled knob",
    keywords: ["knob", "dial", "grip", "handle", "control", "twist"],
    lesson:
      "Organic form via revolve-like stacking + polar finger scallops; tactile chamfers; a height:diameter proportion that reads as designed.",
    code: [
      "from build123d import *",
      "",
      "dia = 35           # power-grip-friendly diameter",
      "height = 18",
      "scallop_r = 3.0",
      "n_scallops = 12",
      "shaft_d = 6.2      # press-fit onto a 6 mm shaft",
      "",
      "with BuildPart() as part:",
      "    Cylinder(dia / 2, height)",
      "    chamfer(part.edges().group_by(Axis.Z)[-1], 2.0)  # crowned top edge",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 1.0)   # base",
      "    # finger scallops around the rim",
      "    with PolarLocations(dia / 2, n_scallops):",
      "        Cylinder(scallop_r, height, mode=Mode.SUBTRACT)",
      "    # shaft bore from the bottom",
      "    with Locations(part.faces().sort_by(Axis.Z)[0]):",
      "        Hole(shaft_d / 2, depth=height - 3)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "divider_tray",
    title: "Compartment tray",
    keywords: ["tray", "organizer", "divider", "compartment", "holder", "caddy", "bin"],
    lesson:
      "Repeated-feature rhythm via a grid, consistent internal corner radii, even rim, draftable walls — coherence across an array of pockets.",
    code: [
      "from build123d import *",
      "",
      "length, width, height = 120, 80, 30",
      "wall = 2.0",
      "cols, rows = 3, 2",
      "inner_r = 3.0      # one internal corner radius, reused",
      "",
      "with BuildPart() as part:",
      "    Box(length, width, height)",
      "    fillet(part.edges().filter_by(Axis.Z), 5.0)",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 1.0)",
      "    pocket_l = (length - wall * (cols + 1)) / cols",
      "    pocket_w = (width - wall * (rows + 1)) / rows",
      "    with BuildSketch(part.faces().sort_by(Axis.Z)[-1]):",
      "        with GridLocations(pocket_l + wall, pocket_w + wall, cols, rows):",
      "            RectangleRounded(pocket_l, pocket_w, inner_r)",
      "    extrude(amount=-(height - wall), mode=Mode.SUBTRACT)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "lofted_vase",
    title: "Lofted vase",
    keywords: ["vase", "vessel", "pot", "planter", "cup", "organic", "lofted"],
    lesson:
      "Smooth swept form via loft between offset profiles, thin-wall shell, tangent transitions — pushes beyond box-and-fillet output.",
    code: [
      "from build123d import *",
      "",
      "base_d = 50",
      "waist_d = 38",
      "rim_d = 56",
      "height = 120",
      "wall = 2.4",
      "",
      "with BuildPart() as part:",
      "    with BuildSketch(Plane.XY):",
      "        Circle(base_d / 2)",
      "    with BuildSketch(Plane.XY.offset(height * 0.45)):",
      "        Circle(waist_d / 2)",
      "    with BuildSketch(Plane.XY.offset(height)):",
      "        Circle(rim_d / 2)",
      "    loft()",
      "    top = part.faces().sort_by(Axis.Z)[-1]",
      "    offset(amount=-wall, openings=top)",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 1.0)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "enclosure_two_part",
    title: "Two-part electronics enclosure (base + lid)",
    keywords: ["enclosure", "case", "housing", "box", "lid", "base", "two-part", "two part", "electronics", "project box", "cover", "assembly"],
    lesson:
      "Multi-part assembly via a `parts` dict: a shelled base (open top, corner PCB standoffs, a side port cutout) plus a lid whose underside lip drops inside the walls with a printed-fit clearance; one corner-radius family reused across both parts.",
    code: [
      "from build123d import *",
      "",
      "# Two-part electronics enclosure. One corner-radius family across both parts;",
      "# the lid drops into the base with a printed-fit clearance.",
      "length, width = 90, 60",
      "base_h = 26",
      "lid_h = 6",
      "wall = 2.4",
      "corner_r = 8.0            # reused on every vertical edge",
      "edge_break = 1.0",
      "base_chamfer = 1.0",
      "fit_gap = 0.25            # lid-lip clearance to the base inner wall",
      "boss_d = 7.0             # corner PCB standoff outer diameter",
      "pilot_r = 1.1            # M2 self-tap pilot",
      "port_w, port_h = 12.0, 7.0   # side port cutout (e.g. USB-C)",
      "",
      "# ---- base: shelled box, open top, corner standoffs, one side port ----",
      "with BuildPart() as base:",
      "    Box(length, width, base_h)",
      "    fillet(base.edges().filter_by(Axis.Z), corner_r)",
      "    chamfer(base.edges().group_by(Axis.Z)[0], base_chamfer)",
      "    top = base.faces().sort_by(Axis.Z)[-1]",
      "    offset(amount=-wall, openings=top)",
      "    # corner standoffs rising from the floor",
      "    inset_x = length / 2 - wall - boss_d / 2 - 1.5",
      "    inset_y = width / 2 - wall - boss_d / 2 - 1.5",
      "    floor_z = -base_h / 2",
      "    with Locations(",
      "        (inset_x, inset_y, floor_z), (-inset_x, inset_y, floor_z),",
      "        (inset_x, -inset_y, floor_z), (-inset_x, -inset_y, floor_z),",
      "    ):",
      "        Cylinder(boss_d / 2, base_h - wall, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "        Cylinder(pilot_r, base_h - wall, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
      "    # side port cutout through one long wall",
      "    with Locations(Plane.YZ):",
      "        with Locations((0, 0, length / 2)):",
      "            Box(port_w, port_h, wall * 3, mode=Mode.SUBTRACT)",
      "",
      "# ---- lid: top plate + inner lip that drops into the base ----",
      "inner = min(length, width) - 2 * wall - 2 * fit_gap",
      "with BuildPart() as lid:",
      "    Box(length, width, lid_h)",
      "    fillet(lid.edges().filter_by(Axis.Z), corner_r)",
      "    fillet(lid.edges().group_by(Axis.Z)[-1], edge_break)",
      "    # inner lip frame on the underside",
      "    bottom = lid.faces().sort_by(Axis.Z)[0]",
      "    with BuildSketch(bottom):",
      "        Rectangle(length - 2 * wall - 2 * fit_gap, width - 2 * wall - 2 * fit_gap)",
      "        Rectangle(length - 4 * wall - 2 * fit_gap, width - 4 * wall - 2 * fit_gap, mode=Mode.SUBTRACT)",
      "    extrude(amount=lid_h)",
      "",
      "parts = {\"base\": base.part, \"lid\": lid.part}",
    ].join("\n"),
    verified: true,
  },
  {
    id: "mounting_standoffs",
    title: "Mounting baseplate with standoffs",
    keywords: ["standoff", "standoffs", "boss", "bosses", "mount", "mounting", "pcb", "board", "baseplate", "plate", "screw boss"],
    lesson:
      "Standoff/boss building block: a filleted plate with a grid of board standoffs (drilled pilot holes) and counterbored corner mounting holes, all from one screw/boss size family — composable into enclosures.",
    code: [
      "from build123d import *",
      "",
      "# Mounting baseplate: a filleted plate with a 2x2 grid of board standoffs",
      "# (counter-drilled pilot holes) and corner mounting holes counterbored for",
      "# screw heads. One screw/boss size family, parametrically placed \u2014 the reusable",
      "# building block for mounting a PCB or module inside an enclosure.",
      "plate_l, plate_w = 70, 50",
      "plate_t = 3.0",
      "corner_r = 4.0",
      "boss_d = 8.0",
      "boss_h = 6.0            # lifts the board off the plate",
      "pilot_r = 1.25         # M2.5 self-tap pilot into the boss",
      "mount_r = 1.6          # M3 clearance at the corners",
      "cbore_r = 3.2          # screw-head counterbore",
      "cbore_depth = 2.0",
      "board_l, board_w = 50, 30   # standoff grid footprint",
      "",
      "with BuildPart() as part:",
      "    Box(plate_l, plate_w, plate_t)",
      "    fillet(part.edges().filter_by(Axis.Z), corner_r)",
      "    top = part.faces().sort_by(Axis.Z)[-1]",
      "    # standoffs up from the top face on a rectangular grid",
      "    with BuildSketch(top):",
      "        with GridLocations(board_l, board_w, 2, 2):",
      "            Circle(boss_d / 2)",
      "    extrude(amount=boss_h)",
      "    # pilot holes down each standoff",
      "    with Locations(part.faces().sort_by(Axis.Z)[-1]):",
      "        with GridLocations(board_l, board_w, 2, 2):",
      "            Hole(pilot_r, depth=boss_h + plate_t - 0.6)",
      "    # corner mounting holes, counterbored from the top for the screw head",
      "    mx = plate_l / 2 - corner_r - 2.5",
      "    my = plate_w / 2 - corner_r - 2.5",
      "    with Locations(top):",
      "        with Locations((mx, my), (-mx, my), (mx, -my), (-mx, -my)):",
      "            CounterBoreHole(mount_r, cbore_r, cbore_depth)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "gyroid_tpms_core",
    title: "Gyroid TPMS core (mesh mode)",
    keywords: ["gyroid", "tpms", "lattice", "lattices", "minimal surface", "heat exchanger", "heat-exchanger", "infill", "porous", "mesh"],
    lesson:
      "Mesh mode for geometry the CAD kernel cannot express (TPMS / lattice / heat-exchanger core / organic field): sample an implicit gyroid field on a grid, pad it with void so the surface closes, and marching-cubes it into a watertight trimesh assigned to `result` — not build123d.",
    code: [
      "# MESH MODE: a gyroid TPMS core \u2014 a triply-periodic minimal surface the CAD",
      "# kernel (build123d) cannot express. Build it as an implicit field sampled on a",
      "# grid, then marching-cubes it into a watertight trimesh. This is the right tool",
      "# for lattices / heat-exchanger cores / infills.",
      "import numpy as np",
      "import trimesh",
      "from skimage import measure",
      "",
      "size = 40.0          # cube edge (mm)",
      "cells = 3            # gyroid unit cells per axis",
      "wall = 0.45          # half sheet-thickness control (larger = thicker walls)",
      "n = 96               # grid resolution per axis (keep <= ~120 for speed)",
      "",
      "lin = np.linspace(0.0, 2.0 * np.pi * cells, n)",
      "x, y, z = np.meshgrid(lin, lin, lin, indexing=\"ij\")",
      "g = np.sin(x) * np.cos(y) + np.sin(y) * np.cos(z) + np.sin(z) * np.cos(x)",
      "",
      "# Solid where |g| <= wall -> a thin double-walled gyroid SHEET (two fluid",
      "# networks separated by one surface). Negative = solid, positive = void.",
      "field = np.abs(g) - wall",
      "# Pad with \"void\" so marching cubes closes the surface at the box boundary,",
      "# yielding a watertight solid instead of an open shell.",
      "field = np.pad(field, 1, mode=\"constant\", constant_values=1.0)",
      "",
      "verts, faces, _, _ = measure.marching_cubes(field, level=0.0)",
      "# Map voxel-index coords to mm (account for the 1-voxel pad on each side).",
      "verts = (verts - 1.0) / (n - 1.0) * size",
      "mesh = trimesh.Trimesh(vertices=verts, faces=faces)",
      "mesh.merge_vertices()",
      "mesh.fix_normals()",
      "# Marching cubes can leave sub-voxel debris bodies (closed slivers with",
      "# ~zero volume) where the field grazes the grid. Drop them — one printed",
      "# part must be ONE fused body.",
      "bodies = mesh.split(only_watertight=False)",
      "if len(bodies) > 1:",
      "    keep = [b for b in bodies if abs(float(b.volume)) > 1.0]",
      "    mesh = trimesh.util.concatenate(keep) if len(keep) > 1 else keep[0]",
      "",
      "result = mesh",
    ].join("\n"),
    verified: true,
  },
  {
    id: "tapered_device_enclosure",
    title: "Tapered device enclosure",
    keywords: ["device", "gadget", "enclosure", "case", "tapered", "puck", "housing", "wearable", "remote"],
    lesson:
      "Premium product surfacing: a gentle draft (top slightly inset from the base) with one unified corner-radius family, a softened crowned top rim and a small base relief, manually shelled. Restraint over detail — one cohesive flowing body.",
    code: [
      "from build123d import *",
      "length, width, height = 90, 55, 24",
      "top_inset = 4          # top smaller than base -> gentle premium draft",
      "corner_r = 12.0",
      "wall = 2.0",
      "with BuildPart() as part:",
      "    with BuildSketch(Plane.XY):",
      "        RectangleRounded(length, width, corner_r)",
      "    with BuildSketch(Plane.XY.offset(height)):",
      "        RectangleRounded(length - 2 * top_inset, width - 2 * top_inset, corner_r - 1)",
      "    loft()",
      "    fillet(part.edges().group_by(Axis.Z)[-1], 2.0)   # softened top rim",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 0.8)   # base relief",
      "    # hollow: subtract an inner tapered loft, open at the top",
      "    with BuildSketch(Plane.XY.offset(wall)):",
      "        RectangleRounded(length - 2 * wall, width - 2 * wall, corner_r - wall)",
      "    with BuildSketch(Plane.XY.offset(height + 1)):",
      "        RectangleRounded(length - 2 * top_inset - 2 * wall, width - 2 * top_inset - 2 * wall, max(0.6, corner_r - 1 - wall))",
      "    loft(mode=Mode.SUBTRACT)",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "soft_catch_all_tray",
    title: "Soft catch-all tray",
    keywords: ["catch-all", "catchall", "valet", "dish", "tray", "pebble", "bowl", "organizer", "desk"],
    lesson:
      "Soft, cohesive product form: a very generous unified corner radius with a soft top rim and base, and a shallow bowl pocket — one pebble-like flowing body. The pocket is cut (not shelled): shelling through a big pre-filleted rim silently seals the opening into a closed hollow, so the bowl is an explicit rounded pocket inset by wall + rim radius.",
    code: [
      "from build123d import *",
      "length, width, height = 110, 80, 26",
      "corner_r = 26.0        # very soft, pebble-like corners",
      "wall = 2.2",
      "rim_r = 6.0            # soft top rim",
      "with BuildPart() as part:",
      "    Box(length, width, height, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "    fillet(part.edges().filter_by(Axis.Z), corner_r)",
      "    fillet(part.edges().group_by(Axis.Z)[-1], rim_r)   # soft top rim",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 3.0)     # soft base",
      "    # Bowl as an explicit rounded pocket: shelling through the big rim",
      "    # fillet silently produces a CLOSED hollow (the opening seals), so cut",
      "    # the pocket instead — inset by wall + rim_r so the soft rim keeps a",
      "    # full wall everywhere along its curve.",
      "    with BuildSketch(Plane.XY.offset(height + 1)):",
      "        RectangleRounded(length - 2 * wall - 2 * rim_r,",
      "                         width - 2 * wall - 2 * rim_r,",
      "                         corner_r - wall - rim_r)",
      "    extrude(amount=-(height + 1 - wall), mode=Mode.SUBTRACT)",
      "    fillet(part.edges().group_by(Axis.Z)[-1], 1.0)     # break the mouth",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "organic_sdf_bracket",
    title: "Organic load-path bracket (SDF skeleton + skin)",
    keywords: ["bracket", "mount", "mounting", "organic", "topology", "optimized", "lightweight", "lightweighted", "link", "arm", "sculptural"],
    lesson:
      "Organic-functional via the SDF toolkit: EXACT bolt bosses + holes (tolerances embedded) smooth-unioned (smin) with a load-path web of capsule struts, marching-cubed to a watertight mesh. A flowing, optimized-looking form with real functional features, not joined primitives.",
    code: [
      "from sdf_kit import *",
      "",
      "T = 12.0          # thickness",
      "boss_r, hole_r = 9.0, 2.7      # exact boss + M5 clearance",
      "A, B = (-40.0, 0.0), (40.0, 0.0)",
      "strut_r, k = 4.5, 7.0",
      "top, bot = (0.0, 18.0), (0.0, -18.0)",
      "",
      "def field(P):",
      "    z0, z1 = -T/2, T/2",
      "    # exact functional bosses",
      "    f = smin(cyl_z(P, A[0], A[1], boss_r, z0, z1),",
      "             cyl_z(P, B[0], B[1], boss_r, z0, z1), k)",
      "    # organic load-path web (arches + central brace)",
      "    for (p, q) in [(A, top), (top, B), (A, bot), (bot, B)]:",
      "        a3 = (p[0], p[1], 0.0); b3 = (q[0], q[1], 0.0)",
      "        f = smin(f, capsule(P, (a3[0], a3[1], z0), (a3[0], a3[1], z1), strut_r), k)",
      "        f = smin(f, capsule(P, a3, b3, strut_r), k)",
      "    f = smin(f, capsule(P, (top[0], top[1], 0.0), (bot[0], bot[1], 0.0), strut_r*0.7), k)",
      "    # exact bolt holes (through)",
      "    for c in (A, B):",
      "        f = subtract(f, cyl_z(P, c[0], c[1], hole_r, -T, T))",
      "    return f",
      "",
      "result = to_mesh(field, (-56, -30, -T), (56, 30, T), pitch=0.6)",
    ].join("\n"),
    verified: true,
  },
  {
    id: "sdf_smooth_handle",
    title: "Smooth product form via SDF (cabinet pull)",
    keywords: ["handle", "pull", "grip", "knob", "door handle", "drawer pull", "lever", "smooth", "premium"],
    lesson:
      "Beautiful PRODUCT design via SDF (taste first, not topology-optimized struts): mount posts + a gently bowed grip smooth-unioned into ONE flowing premium body, with exact screw holes. Structure shows only as the clean post-to-grip transition.",
    code: [
      "from sdf_kit import *",
      "",
      "# A smooth, premium cabinet/drawer pull: two mount posts off a back face + a",
      "# gently bowed grip, all smooth-unioned into one flowing body. Beauty first;",
      "# the only \"structure\" is the clean post-to-grip transition.",
      "post_r, grip_r = 6.0, 7.0",
      "screw_r = 2.2",
      "standoff = 22.0",
      "A, B = (-50.0, 0.0), (50.0, 0.0)",
      "k = 8.0",
      "",
      "def field(P):",
      "    # mount posts (exact), up from the back face z=0",
      "    f = smin(cyl_z(P, A[0], A[1], post_r, 0.0, standoff),",
      "             cyl_z(P, B[0], B[1], post_r, 0.0, standoff), k)",
      "    # gently bowed grip (two capsules meeting at a raised midpoint -> smooth bow)",
      "    mid = (0.0, 0.0, standoff + 7.0)",
      "    f = smin(f, capsule(P, (A[0], A[1], standoff), mid, grip_r), k)",
      "    f = smin(f, capsule(P, mid, (B[0], B[1], standoff), grip_r), k)",
      "    # exact screw holes from the back, into the posts",
      "    for c in (A, B):",
      "        f = subtract(f, cyl_z(P, c[0], c[1], screw_r, -2.0, 15.0))",
      "    return f",
      "",
      "result = to_mesh(field, (-60, -12, -3), (60, 12, 34), pitch=0.6)",
    ].join("\n"),
    verified: true,
  },
  {
    id: "gyroid_heat_exchanger_core",
    title: "Two-fluid gyroid heat-exchanger core (sdf_kit v2)",
    keywords: ["heat exchanger", "heat-exchanger", "exchanger", "two fluid", "two-fluid", "counterflow", "coolant", "manifold", "gyroid", "tpms", "radiator", "intercooler"],
    lesson:
      "sdf_kit v2 composition for dual-network parts: an OPEN-ENDED cylindrical jacket tube whose interior is filled by a gyroid SHEET via mask() — the sheet splits the inner volume into two interpenetrating, fully isolated fluid labyrinths (verify with check_networks). Ends stay open: a capped core would seal both labyrinths into trapped, unprintable voids. The sheet region overlaps half a wall into the tube so the meshed sheet fuses into one body.",
    code: [
      "# MESH MODE (sdf_kit): a two-fluid gyroid heat-exchanger CORE — an open-ended",
      "# jacket tube whose interior is split by a gyroid sheet into TWO isolated",
      "# fluid labyrinths. The sheet is the heat-transfer surface; manifolds attach",
      "# at the open ends. The ends MUST stay open — capping the tube would seal",
      "# both labyrinths into trapped voids no printer can evacuate.",
      "from sdf_kit import *",
      "",
      "core_d = 50.0        # jacket outer diameter",
      "core_h = 60.0        # core height",
      "wall = 2.0           # jacket wall",
      "cell = 12.0          # gyroid unit cell (mm) — smaller = more surface, more back-pressure",
      "sheet_t = 1.6        # separating sheet thickness (min printable wall)",
      "",
      "R = core_d / 2",
      "",
      "def field(P):",
      "    # Jacket: an open-ended tube (inner cut overshoots both ends).",
      "    tube = subtract(",
      "        cyl_z(P, 0, 0, R, 0.0, core_h),",
      "        cyl_z(P, 0, 0, R - wall, -1.0, core_h + 1.0),",
      "    )",
      "    # Gyroid separating SHEET (|g| <= t), clipped to a region that overlaps",
      "    # half a wall INTO the tube — a hard clip exactly at the wall face can",
      "    # leave the sheet a disconnected body at mesh resolution. The sheet",
      "    # splits the interior into two networks that never touch — verify with",
      "    # check_networks before trusting it.",
      "    region = cyl_z(P, 0, 0, R - wall / 2, 0.0, core_h)",
      "    sheet = mask(gyroid(P, cell, sheet_t), region)",
      "    return union(tube, sheet)",
      "",
      "result = to_mesh(field, (-R - 2, -R - 2, -2), (R + 2, R + 2, core_h + 2), pitch=0.6)",
    ].join("\n"),
    verified: true,
  },
  {
    id: "draped_component_enclosure",
    title: "Enclosure draped over a component stack (sdf_kit)",
    keywords: ["enclosure", "case", "housing", "drape", "draped", "organic", "component", "components", "pcb", "battery", "stack", "electronics", "skin", "pod"],
    lesson:
      "The default-taste move: exact component keep-outs (boxes + clearance) smooth-unioned into ONE cavity, then the skin = offset_field(cavity, wall) — a flowing organic body whose interior fits are exact. Flat base cut for printing, crisp port subtracted last. Verified: watertight AND every component corner inside the cavity.",
    code: [
      "# ORGANIC-FUNCTIONAL (sdf_kit): an enclosure DRAPED over a component stack.",
      "# Exact keep-outs (component boxes + clearance) define the cavity; the skin",
      "# is the cavity grown by one wall, with a large smin blend so the body reads",
      "# as one flowing form instead of two boxes glued together. Function first \u2014",
      "# the fits are exact; the beauty is the drape.",
      "from sdf_kit import *",
      "import numpy as np",
      "",
      "# Components (exact, mm): a 62x42x12 PCB with a 50x30x13 battery above it.",
      "pcb_c, pcb_h = (0.0, 0.0, 8.0), (31.0, 21.0, 6.0)",
      "batt_c, batt_h = (0.0, 0.0, 20.5), (25.0, 15.0, 6.5)",
      "clearance = 1.0",
      "wall = 2.4",
      "k = 14.0            # blend radius: bigger = softer drape over the stack",
      "",
      "def field(P):",
      "    # Functional envelope: each keep-out grown by clearance, smooth-unioned",
      "    # so the skin flows over the stack.",
      "    cavity = smin(",
      "        box(P, pcb_c, tuple(h + clearance for h in pcb_h)),",
      "        box(P, batt_c, tuple(h + clearance for h in batt_h)),",
      "        k,",
      "    )",
      "    body = offset_field(cavity, wall)      # the drape: cavity + one wall",
      "    shell = subtract(body, cavity)",
      "    shell = np.maximum(shell, -P[:, 2])    # flat printable base at z=0",
      "    # Exact USB-C cutout through the front wall at PCB height.",
      "    port = box(P, (0.0, -24.0, 8.0), (6.5, 6.0, 2.6))",
      "    return subtract(shell, port)",
      "",
      "result = to_mesh(field, (-40, -30, -4), (40, 30, 34), pitch=0.55)",
    ].join("\n"),
    verified: true,
  },
  {
    id: "draped_two_piece_enclosure",
    title: "Two-piece draped enclosure (drape-and-split recipe)",
    keywords: ["enclosure", "two piece", "two-piece", "case", "housing", "lid", "snap", "split", "clamshell", "shell", "pcb", "battery", "components", "drape", "organic", "electronics"],
    lesson:
      "THE default enclosure archetype: component keep-outs -> smin cavity -> offset_field skin (uniform wall) -> split_shell into two watertight printed-fit halves on an inner lip (clearance is a real, numerically asserted tolerance). Function leads beauty — the organic form IS the softened component stack. Interior stays crisp per the edge budget.",
    code: [
      "# THE DRAPE-AND-SPLIT RECIPE (default enclosure archetype): exact component",
      "# keep-outs smooth-unioned into ONE cavity, an organic skin draped over it",
      "# (offset_field = uniform wall), then split_shell cuts it into two watertight",
      "# printed-fit halves on an inner lip. Function leads beauty: the form IS the",
      "# component stack, softened.",
      "from sdf_kit import *",
      "import numpy as np",
      "",
      "# Components (exact, mm): 62x42x12 PCB, 50x30x13 battery above it.",
      "pcb_c, pcb_h = (0.0, 0.0, 8.0), (31.0, 21.0, 6.0)",
      "batt_c, batt_h = (0.0, 0.0, 20.5), (25.0, 15.0, 6.5)",
      "clearance = 1.0",
      "wall = 2.4",
      "k = 14.0            # drape blend",
      "z_split = 16.0      # seam on the natural shadow line between the two bodies",
      "fit_gap = 0.25      # printed lip clearance",
      "",
      "def cavity(P):",
      "    return smin(box(P, pcb_c, tuple(h + clearance for h in pcb_h)),",
      "                box(P, batt_c, tuple(h + clearance for h in batt_h)), k)",
      "",
      "def body(P):",
      "    shell = subtract(offset_field(cavity(P), wall), cavity(P))",
      "    return np.maximum(shell, -P[:, 2])   # flat printable base",
      "",
      "bottom, top = split_shell(body, cavity, z_split, fit_gap=fit_gap)",
      "lo, hi = (-40, -30, -3), (40, 30, 34)",
      "parts = {",
      "    \"shell_bottom\": to_mesh(bottom, lo, hi, pitch=0.55),",
      "    \"shell_top\": to_mesh(top, lo, hi, pitch=0.55),",
      "}",
    ].join("\n"),
    verified: true,
  },
  {
    id: "pico_dev_board_enclosure",
    title: "Raspberry Pi Pico enclosure (true board datums, drape-and-split)",
    keywords: ["pico", "raspberry pi", "esp32", "arduino", "dev board", "devboard", "microcontroller", "mcu", "board", "enclosure", "case", "usb", "electronics", "two piece", "two-piece"],
    lesson:
      "Dev-board case v3, dimension-audited: every datum numerically asserted (board-corner clearance inside the superellipse plan, USB plug reach <= 3mm from outer face to receptacle, M2x4 pilot depth). Plan exponent n is SOLVED from corner fit, not picked. Bosses at the board's true hole grid (Pico 47.0 x 11.4mm); cavity is a soft superellipse so the offset skin is soft; base AND top rims blended (crisp only at the parting seam); USB = tight aperture + flared overmold relief cut AFTER the split so both halves holster the plug. Swap datums for ESP32/Arduino.",
    code: [
      "# Raspberry Pi Pico enclosure v3 — dimension-audited drape-and-split.",
      "# Changes vs v2 from the audit:",
      "#   - cavity resized 60x28 -> 54.5x28 (cav_a 27.25): the centered board left a",
      "#     4.5mm standoff at the USB end, so a micro-B plug barrel (~9mm from",
      "#     overmold to tip, ~5mm engagement) barely reached the receptacle. Now the",
      "#     outer-face-to-receptacle distance is 2.45mm — any plug seats fully.",
      "#   - plan exponent n solved from corner fit (board corners must clear the",
      "#     superellipse): n=5.5 with b=14 gives 0.78mm corner clearance.",
      "#   - pilot deepened to 3.0mm for an M2x4 self-tapper (was 2.1 — screw",
      "#     bottomed out).",
      "#   - overmold relief 12.5x9 (was 12x8; large plug overmolds run 10.7x8.5).",
      "#   - soft top-rim blend on the skin (crisp edges only at the parting seam).",
      "from sdf_kit import *",
      "import numpy as np",
      "",
      "# --- Pico datums (datasheet) ---",
      "brd_l, brd_w, brd_t = 51.0, 21.0, 1.0",
      "hole_dx, hole_dy = 47.0, 11.4        # mounting grid, holes D2.1",
      "usb_rw, usb_rh = 7.6, 2.8            # micro-B receptacle shell",
      "usb_overhang = 1.3                   # receptacle protrudes past board edge",
      "comp_h, boss_h = 4.0, 2.5",
      "lip_t, lip_h = 1.0, 2.4          # split_shell lip ring",
      "min_wall = 1.5",
      "# split_shell cuts the lid's lip recess INTO the wall, leaving",
      "# wall - lip_t - fit_gap of skirt: size the wall for it (was 2.0 -> 0.75mm skirt)",
      "wall = min_wall + lip_t + 0.25",
      "pilot_r, boss_r = 0.8, 2.4           # pilot D1.6 = 0.8x d for M2 self-tap",
      "fit_gap = 0.25",
      "",
      "# cavity: superellipse solved for corner fit at minimal width",
      "cav_a, cav_b, cav_n = 27.25, 14.0, 5.5",
      "cav_z0 = wall                        # floor = wall (was 1.0mm: under the 1.5mm print minimum)",
      "brd_z = cav_z0 + boss_h              # 3.5 board underside",
      "cav_top = brd_z + brd_t + comp_h + 1.0",
      "z_split = brd_z + brd_t + 1.2",
      "",
      "# --- numeric audit (fails loudly if any datum breaks) ---",
      "def se(x, y):  # superellipse value; <1 = inside plan",
      "    return (abs(x)/cav_a)**cav_n + (abs(y)/cav_b)**cav_n",
      "for cx, cy in [(brd_l/2, brd_w/2)]:",
      "    assert se(cx, cy) < 0.9, \"board corner does not clear cavity plan\"",
      "for bx, by in [(hole_dx/2 + boss_r, hole_dy/2 + boss_r)]:",
      "    assert se(bx, by) < 1.0, \"boss escapes cavity plan\"",
      "# measured from the overmold relief floor (where the plug body stops), not the",
      "# outer wall face: the relief pocket is cut into the wall around the port",
      "relief_floor_x = -(cav_a + wall) - 0.6 + wall*0.62",
      "plug_reach = (-(brd_l/2) - usb_overhang) - relief_floor_x",
      "assert plug_reach <= 3.0, f\"USB plug reach {plug_reach} too deep to engage\"",
      "pilot_z0 = 0.5",
      "assert brd_z - pilot_z0 >= 2.9, \"pilot too shallow for M2x4 engagement\"",
      "",
      "def cavity(P):",
      "    return sq_prism(P, cav_a, cav_b, cav_n, cav_z0, cav_top)",
      "",
      "def body(P):",
      "    f = subtract(offset_field(cavity(P), wall), cavity(P))",
      "    f = np.maximum(f, -P[:, 2])                          # base plane",
      "    f = smax(f, -P[:, 2] - 1.0, 1.4)                     # soft base rim",
      "    f = smax(f, P[:, 2] - (cav_top + wall + 0.6), 2.0)   # soft top rim",
      "    for sx in (-1, 1):",
      "        for sy in (-1, 1):",
      "            f = union(f, cyl_z(P, sx*hole_dx/2, sy*hole_dy/2, boss_r, cav_z0 - 0.2, brd_z))",
      "            f = subtract(f, cyl_z(P, sx*hole_dx/2, sy*hole_dy/2, pilot_r, pilot_z0, brd_z + 0.01))",
      "    return f",
      "",
      "# USB: tight aperture (receptacle +0.5/+0.4 clearance) + flared overmold",
      "# relief, both cut AFTER the split so nothing bridges the plug.",
      "usb_w, usb_h = 8.6, 3.6",
      "plug_w, plug_h = 12.5, 9.0",
      "usb_z = brd_z + brd_t + usb_h/2 - 0.4",
      "xw_out = -(cav_a + wall)",
      "",
      "def usb_cut(P):",
      "    tight = box(P, (xw_out, 0, usb_z), (wall + 1.5, usb_w/2, usb_h/2))",
      "    relief = box(P, (xw_out - 0.6, 0, usb_z + 0.8), (wall*0.62, plug_w/2, plug_h/2))",
      "    return union(tight, relief)",
      "",
      "assert wall - lip_t - fit_gap >= min_wall, \"lid skirt thinner than the print minimum\"",
      "_b, _t = split_shell(body, cavity, z_split, lip_h=lip_h, lip_t=lip_t, fit_gap=fit_gap)",
      "bottom = lambda P: subtract(_b(P), usb_cut(P))",
      "top = lambda P: subtract(_t(P), usb_cut(P))",
      "",
      "lo = (-cav_a - 6, -cav_b - 6, -2)",
      "hi = (cav_a + 6, cav_b + 6, cav_top + wall + 3)",
      "parts = {",
      "    \"case_bottom\": to_mesh(bottom, lo, hi, pitch=0.4),",
      "    \"case_top\": to_mesh(top, lo, hi, pitch=0.4),",
      "}"
    ].join("\n"),
    verified: true,
  },
  {
    id: "esp32_pebble_enclosure",
    title: "ESP32 DevKitC pebble enclosure (organic cavity, drape-and-split, self-tapping stilts)",
    keywords: ["esp32", "devkit", "dev board", "devboard", "organic", "pebble", "round", "soft", "rounded", "smooth", "stone", "enclosure", "case", "housing", "two piece", "two-piece", "usb-c", "usb c", "stilts", "standoffs", "self-tapping", "microcontroller"],
    lesson:
      "Organic enclosure done right: the CAVITY is the organic shape (superellipsoid, plan n=3 + profile m=3.5, SOLVED as the smallest pebble clearing every board datum at <=0.94) and the skin is offset_field(cavity, wall), so outside and inside are both soft and the wall is even. A squircle plan (n>=4) or a rounded box reads as a tray, which is what the model produced before. Wall is sized for split_shell's lip recess (wall >= min_wall + lip_t + fit_gap) or the seam prints paper-thin. Board has no mounting holes, so self-tapping stilts sit at the corners clear of the header rows and are clipped to the cavity so they can't poke through the curved underside. Exact USB-C stadium aperture + overmold relief cut from both halves after meshing.",
    code: [
      "# ESP32-DevKitC (38-pin, USB-C) pebble enclosure: two-piece drape-and-split",
      "# around an ORGANIC cavity. The cavity is a superellipsoid solved to be the",
      "# smallest pebble that clears every board datum; the skin is that cavity",
      "# offset by the wall, so the outside is as soft as the inside and the wall",
      "# is even everywhere. Every datum is asserted, so a bad edit fails loudly.",
      "from sdf_kit import *",
      "import numpy as np",
      "",
      "# --- board datums (ESP32-DevKitC 38-pin, USB-C variant) ---",
      "brd_l, brd_w, brd_t = 55.0, 28.0, 1.6",
      "pin_row_y = 25.4 / 2            # header rows, 1in apart",
      "pin_half_x = 19 * 2.54 / 2      # 19-pin rows: pins span |x| <= 24.1",
      "pin_drop = 8.5                  # male header pins below the PCB",
      "comp_h = 4.0                    # tallest top-side part (buttons / USB-C)",
      "usb_w, usb_h = 8.94, 3.26       # USB-C receptacle shell",
      "usb_overhang = 1.0              # receptacle lip past the board edge",
      "wroom = (18.0, 25.5, 3.1)       # module footprint + height, antenna end at +x",
      "",
      "# --- enclosure parameters ---",
      "min_wall = 1.5                  # printable minimum (DFM target)",
      "lip_t, lip_h = 1.2, 2.4         # split_shell lip ring (innermost lip_t of the wall)",
      "fit_gap = 0.25",
      "# split_shell cuts the lid's recess INTO the wall, leaving wall - lip_t - gap",
      "# of skirt. Size the wall for that, or the seam prints paper-thin.",
      "wall = min_wall + lip_t + fit_gap + 0.1          # 3.05",
      "floor_z = 0.0                   # outer base plane",
      "cav_floor = floor_z + wall      # 2.2",
      "brd_z = cav_floor + pin_drop + 1.5      # board underside (pins clear the floor)",
      "brd_top = brd_z + brd_t",
      "cav_top = brd_top + comp_h + 1.2",
      "x_off = -0.6                    # board shifted toward the USB wall",
      "",
      "# Cavity: a superellipsoid pebble. Exponents SOLVED for the smallest pebble",
      "# that clears every board datum at <= 0.94 of the cavity: plan n=3 (a",
      "# squircle, n>=4, reads as a box) and vertical m=3.5 (m=2 would be an",
      "# ellipsoid, too tall for a flat board; m>=5 gives slab sides).",
      "cav_a, cav_b, cav_n = 36.5, 20.0, 3.0",
      "cav_zc, cav_c, cav_m = (cav_floor + cav_top) / 2 - 0.6, 9.5, 3.5",
      "",
      "def cavity(P):",
      "    d = superellipsoid(P, (0, 0, cav_zc), (cav_a, cav_b, cav_c), cav_n, cav_m)",
      "    return smax(d, cav_floor - P[:, 2], 1.0)        # flat, soft-cornered floor",
      "",
      "# --- numeric fit audit: every datum inside the cavity with clearance ---",
      "def inside(pts, margin):",
      "    return (cavity(np.asarray(pts, float)) < -margin).all()",
      "",
      "hx, hy = brd_l / 2, brd_w / 2",
      "corners = [(x_off + sx * hx, sy * hy, z) for sx in (-1, 1) for sy in (-1, 1)",
      "           for z in (brd_z, brd_top)]",
      "assert inside(corners, 0.4), \"board corner hits the cavity\"",
      "pins = [(x_off + sx * pin_half_x, sy * pin_row_y, brd_z - pin_drop)",
      "        for sx in (-1, 1) for sy in (-1, 1)]",
      "assert inside(pins, 0.3), \"header pin tips hit the cavity\"",
      "wx0 = x_off + hx - wroom[1]",
      "module = [(x, sy * wroom[0] / 2, brd_top + wroom[2]) for x in (wx0, x_off + hx) for sy in (-1, 1)]",
      "assert inside(module, 0.5), \"ESP32 module hits the lid\"",
      "tall = [(x_off - hx + 4, sy * 4, brd_top + comp_h) for sy in (-1, 1)]",
      "assert inside(tall, 0.5), \"buttons / USB-C hit the lid\"",
      "",
      "# --- outer skin: the cavity offset by the wall, flat stable base ---",
      "def body(P):",
      "    f = subtract(offset_field(cavity(P), wall), cavity(P))",
      "    return smax(f, floor_z - P[:, 2], 1.2)",
      "",
      "# --- self-tapping stilts at the board corners, clear of the header rows ---",
      "stilt_r = 2.6",
      "pilot_r = 0.8                   # M2 self-tapper pilot (D1.6)",
      "stilt_xy = [(x_off + sx * (hx + 0.9), sy * (hy + 0.9)) for sx in (-1, 1) for sy in (-1, 1)]",
      "for sx, sy in stilt_xy:",
      "    assert abs(sx - x_off) > pin_half_x + stilt_r, \"stilt collides with header pins\"",
      "",
      "def stilts(P):",
      "    d = None",
      "    for sx, sy in stilt_xy:",
      "        s = cyl_z(P, sx, sy, stilt_r, cav_floor - 1.0, brd_z)",
      "        d = s if d is None else union(d, s)",
      "    return d",
      "",
      "def bottom_field(P):",
      "    # Stilts clipped to the cavity: at the board corners the pebble's",
      "    # underside already curves up, and unclipped posts poked out through",
      "    # the skin as nubs.",
      "    return smin(bottom_half(P), intersect(stilts(P), cavity(P) + 0.3), 1.2)",
      "",
      "bottom_half, top_half = split_shell(body, cavity, brd_top + 1.0, lip_h=lip_h, lip_t=lip_t, fit_gap=fit_gap)",
      "",
      "lo = (-cav_a - wall - 2, -cav_b - wall - 2, floor_z - 1.5)",
      "hi = (cav_a + wall + 2, cav_b + wall + 2, cav_zc + cav_c + wall + 2)",
      "bottom = to_mesh(bottom_field, lo, hi, pitch=0.45)",
      "top = to_mesh(top_half, lo, hi, pitch=0.45)",
      "",
      "# --- exact cuts, after meshing ---",
      "for sx, sy in stilt_xy:",
      "    bottom = mesh_subtract(bottom, mesh_cyl(sx, sy, pilot_r, brd_z - 5.0, brd_z + 1.0))",
      "",
      "# USB-C: stadium aperture (tight) + flared overmold relief, cut from both",
      "# halves so the parting line holsters the plug.",
      "usb_z = brd_top + usb_h / 2",
      "usb_x = x_off - hx - usb_overhang",
      "def stadium_x(x0, x1, zc, w, h):",
      "    r = h / 2",
      "    core = mesh_box(((x0 + x1) / 2, 0, zc), ((x1 - x0) / 2, w / 2 - r, r))",
      "    ends = [mesh_rod((x0, sy * (w / 2 - r), zc), (x1, sy * (w / 2 - r), zc), r) for sy in (-1, 1)]",
      "    return mesh_union(mesh_union(core, ends[0]), ends[1])",
      "tight = stadium_x(usb_x - 12, usb_x + 1.0, usb_z, usb_w + 0.6, usb_h + 0.6)",
      "relief = stadium_x(usb_x - 12, usb_x - 1.6, usb_z, 12.8, 7.2)",
      "cutter = mesh_union(tight, relief)",
      "bottom = mesh_subtract(bottom, cutter)",
      "top = mesh_subtract(top, cutter)",
      "",
      "parts = {\"case_bottom\": bottom, \"case_top\": top}"
    ].join("\n"),
    verified: true,
  },
  {
    id: "beach_scoop_shovel",
    title: "Child's beach shovel (swept dustpan scoop, filleted drain holes, finger-grooved handle)",
    keywords: ["shovel", "scoop", "spade", "trowel", "sand", "beach", "toy", "child", "kid", "kids", "handle", "grip", "ergonomic", "drain", "drainage", "holes", "sieve", "strainer", "colander", "basket", "dustpan", "organic", "fun"],
    lesson:
      "Organic hand tool in one field. The rim height is a FUNCTION of x (deep at the back, shallow lip at the front) instead of a flat top plane, which is what makes it read as a scoop. Every drain hole is smooth-subtracted (smax with a small k), so all hole mouths come out filleted for free, and it's one clean, larger-scale grid rather than a busy pattern. The handle is a capsule chain joined to the basket with ONE blend radius (a flowing neck), with a few broad finger grooves smooth-subtracted underneath (not many small ridges). Flat base plus an underside bevel on the leading edge. The build-volume limit is asserted, not assumed. This exact prompt failed in production on B-rep after 786s as 'printable but visually weak'.",
    code: [
      "# Child's beach shovel: dustpan scoop + drain basket + finger-grooved handle.",
      "# x = forward (scoop front at +x), y = width, z = up; base flat on the bed.",
      "from sdf_kit import *",
      "import numpy as np",
      "",
      "# --- named dimensions ---",
      "build_max = 180.0               # printer cube",
      "basket_a, basket_b = 50.0, 48.0 # plan half-length / half-width (96 wide)",
      "plan_n = 2.8                    # soft plan: reads as a scoop, not a tray",
      "wall = 2.6",
      "rim_back, rim_front = 42.0, 10.0  # deeper at the back, shallow lip up front",
      "lip_bevel = 9.0                 # leading edge thins to scoop into sand",
      "blend = 6.0                     # one family of soft blends for the form",
      "",
      "hole_r, hole_pitch = 3.2, 10.0  # drainage: one clean, larger-scale grid",
      "handle_r = 10.5                 # ~21mm grip: child's hand",
      "knob_r = 12.5",
      "groove_r, groove_depth = 7.0, 4.2",
      "",
      "def rim_height(x):",
      "    t = np.clip((x + basket_a) / (2 * basket_a), 0.0, 1.0)   # 0 back .. 1 front",
      "    return rim_back + (rim_front - rim_back) * t ** 0.8",
      "",
      "# --- basket: outer scoop solid minus the open inner volume ---",
      "def outer_scoop(P):",
      "    plan = sq_prism(P, basket_a, basket_b, plan_n, -1.0, 200.0)",
      "    top = P[:, 2] - rim_height(P[:, 0])          # rim follows the sweep",
      "    d = smax(plan, top, 3.0)",
      "    d = smax(d, -P[:, 2], 1.5)                   # flat base",
      "    # bevel the leading edge underneath so it slices into sand",
      "    bevel = (P[:, 2] - (P[:, 0] - (basket_a - lip_bevel)) * 0.45) * 0.9",
      "    return smax(d, -bevel, 2.0)",
      "",
      "def inner_scoop(P):",
      "    plan = sq_prism(P, basket_a - wall, basket_b - wall, plan_n, wall, 300.0)",
      "    return smax(plan, wall - P[:, 2], 2.0)",
      "",
      "def basket(P):",
      "    return smax(outer_scoop(P), -inner_scoop(P), 0.8)",
      "",
      "# --- drainage: floor holes on a grid + a row through each side wall ---",
      "def drains(P):",
      "    d = None",
      "    xs = np.arange(-basket_a + 12, basket_a - 10, hole_pitch)",
      "    ys = np.arange(-basket_b + 12, basket_b - 11, hole_pitch)",
      "    for x in xs:",
      "        for y in ys:",
      "            if ((abs(x) / (basket_a - 9)) ** plan_n + (abs(y) / (basket_b - 9)) ** plan_n) > 1:",
      "                continue",
      "            c = cyl_z(P, x, y, hole_r, -5.0, wall + 2.0)",
      "            d = c if d is None else union(d, c)",
      "    for x in np.arange(-basket_a + 14, basket_a - 22, hole_pitch * 1.3):",
      "        z = min(rim_height(x) * 0.45, 16.0)",
      "        for sy in (-1, 1):",
      "            c = capsule(P, (x, sy * (basket_b - 8), z), (x, sy * (basket_b + 8), z), hole_r * 0.85)",
      "            d = union(d, c)",
      "    return d",
      "",
      "# --- handle: sweeps up and back from the rear rim, grooves underneath ---",
      "h_pts = [(-basket_a + 6, 0, rim_back - 6), (-basket_a - 22, 0, rim_back + 8),",
      "         (-basket_a - 52, 0, rim_back + 13)]",
      "knob_c = (-basket_a - 58, 0, rim_back + 14)",
      "",
      "def handle(P):",
      "    d = capsule(P, h_pts[0], h_pts[1], handle_r * 1.15)",
      "    d = smin(d, capsule(P, h_pts[1], h_pts[2], handle_r), blend)",
      "    d = smin(d, sphere(P, knob_c, knob_r), 4.0)",
      "    # three broad finger grooves along the underside (fewer, broader scallops)",
      "    a, b = np.array(h_pts[1], float), np.array(h_pts[2], float)",
      "    for t in (0.18, 0.5, 0.82):",
      "        c = a + (b - a) * t + np.array([0, 0, -handle_r - groove_r + groove_depth])",
      "        d = smax(d, -sphere(P, c, groove_r), 2.5)",
      "    return d",
      "",
      "def shovel(P):",
      "    body = smin(basket(P), handle(P), blend)     # one flowing neck",
      "    return smax(body, -drains(P), 1.2)           # soft, filleted hole mouths",
      "",
      "lo = (-basket_a - 75, -basket_b - 4, -2.0)",
      "hi = (basket_a + 4, basket_b + 4, rim_back + 30.0)",
      "result = to_mesh(shovel, lo, hi, pitch=0.7)",
      "",
      "ext = result.extents",
      "assert (ext <= build_max).all(), f\"does not fit the {build_max}mm build cube: {ext}\""
    ].join("\n"),
    verified: true,
  },
  {
    id: "pegboard_double_hook",
    title: "Pegboard double hook (molded tapering prongs, flat mating back, print-validated L-pegs)",
    keywords: ["pegboard", "peg board", "hook", "hooks", "double hook", "prong", "prongs", "tool holder", "pliers", "scissors", "wall hook", "hanger", "organic", "smooth", "swept", "spline", "loft", "bracket"],
    lesson:
      "A product limb is a MOLDED BAR, not a tube: each prong's cross-section is a soft rounded rectangle, taller than wide (stiff in bending), whose height, width and centerline are smooth functions of distance from the pad, so it tapers from a strong root to a slim upturned tip. A round tube swept along a spline reads as a generated sausage, however smooth the spline. The board-bearing back is a MATING FACE: clip it with a hard plane AFTER every blend, because smooth blends bulge material past it (3mm behind the board on an earlier version) and the hook rocks instead of sitting flush; the script asserts nothing but the pegs sits behind the board. The pegboard interface (1/4in holes on 1in centers, 3.2mm board, 4.5mm L-pegs) comes from a revision that was printed and tested on a real board. This prompt family failed four times on B-rep (fillet and loft watertightness errors, 'looks like primitives welded together').",
    code: [
      "# Pegboard double hook for pliers / scissors: a molded part, not swept tubes.",
      "# Peg interface datums are from a print-validated revision; only the form is new.",
      "# Y = out from the board face (0 = board-bearing datum), Z = up, X = across.",
      "from sdf_kit import *",
      "import numpy as np",
      "",
      "# --- validated pegboard interface (printed and tested on the board) ---",
      "hole_d, hole_pitch = 6.35, 25.4      # 1/4\" holes on 1\" centers",
      "board_t, clearance = 3.2, 0.7",
      "peg_d = 4.5",
      "peg_z = 20.0                          # peg centerline height",
      "rear_return = 8.0                     # L-peg rises behind the board",
      "peg_r = peg_d / 2",
      "return_y = -(board_t + clearance + peg_r)          # behind the board",
      "assert peg_d + clearance <= hole_d, \"peg will not pass the hole\"",
      "",
      "# --- mount pad ---",
      "pad_w, pad_h, pad_t = 38.0, 30.0, 5.0",
      "pad_zc = 17.0",
      "pad_n = 4.0                           # squircle outline",
      "pad_edge = 1.8                        # soft front edge",
      "",
      "# --- prongs: molded bars with a designed cross-section ---",
      "# Section is a soft rounded rectangle, TALLER than wide (stiff in bending,",
      "# and it reads as a molded part, not a round tube). Height and width taper",
      "# from a strong root to a slim upturned tip.",
      "prong_gap = 32.0                      # tool slot between prong centers at the tip",
      "reach = 50.0",
      "root_h, tip_h = 7.5, 3.4              # half-heights",
      "root_w, tip_w = 4.2, 2.8              # half-widths",
      "section_round = 0.55                  # corner radius as a fraction of the smaller half-size",
      "rise = 9.0                            # tip lift that keeps tools on",
      "root_z = 11.0",
      "root_blend = 5.0",
      "",
      "def prong_path(y, side):",
      "    \"\"\"Centerline of one prong as smooth functions of y (0 at the pad face).\"\"\"",
      "    t = np.clip(y / reach, 0.0, 1.0)",
      "    x = side * (hole_pitch / 2 + (prong_gap / 2 - hole_pitch / 2) * (3 * t**2 - 2 * t**3))",
      "    z = root_z - 3.0 * np.sin(np.pi * t) + rise * t ** 3        # gentle sag, then lift",
      "    h = root_h + (tip_h - root_h) * (1 - (1 - t) ** 2)          # tapers fast near the root",
      "    w = root_w + (tip_w - root_w) * t",
      "    return x, z, h, w",
      "",
      "def rounded_rect(qx, qz, hw, hh, r):",
      "    dx = np.abs(qx) - (hw - r)",
      "    dz = np.abs(qz) - (hh - r)",
      "    out = np.sqrt(np.maximum(dx, 0) ** 2 + np.maximum(dz, 0) ** 2)",
      "    return out + np.minimum(np.maximum(dx, dz), 0) - r",
      "",
      "def prong(P, side):",
      "    y = P[:, 1]",
      "    x, z, h, w = prong_path(y, side)",
      "    r = section_round * np.minimum(w, h)",
      "    d = rounded_rect(P[:, 0] - x, P[:, 2] - z, w, h, r)",
      "    # round the tip end over the slim section, and start the bar inside the pad",
      "    _, zt, ht, wt = prong_path(np.array([reach]), side)",
      "    d = smax(d, y - reach, float(wt[0]))",
      "    return smax(d, pad_t * 0.4 - y, 0.5)",
      "",
      "def pad(P):",
      "    Q = P[:, [0, 2, 1]] - np.array([0.0, pad_zc, 0.0])   # XZ outline, extruded along Y",
      "    d = sq_prism(Q, pad_w / 2, pad_h / 2, pad_n, 0.0, pad_t)",
      "    return smax(d, P[:, 1] - pad_t, pad_edge)            # soften only the front edge",
      "",
      "def pegs(P):",
      "    d = None",
      "    for x in (-hole_pitch / 2, hole_pitch / 2):",
      "        through = capsule(P, (x, 1.0, peg_z), (x, return_y, peg_z), peg_r)",
      "        up = capsule(P, (x, return_y, peg_z), (x, return_y, peg_z + rear_return), peg_r)",
      "        p = union(through, up)",
      "        d = p if d is None else union(d, p)",
      "    return d",
      "",
      "def hook(P):",
      "    body = smin(pad(P), prong(P, -1), root_blend)",
      "    body = smin(body, prong(P, 1), root_blend)",
      "    # The board-bearing back is a MATING FACE: clip it with a hard plane AFTER",
      "    # every blend. Blends bulge material past it (3mm behind the board on the",
      "    # previous version) and the hook rocks instead of sitting flush.",
      "    body = np.maximum(body, -P[:, 1])",
      "    return union(body, pegs(P))",
      "",
      "lo = (-pad_w / 2 - 4, return_y - 4, -2.0)",
      "hi = (pad_w / 2 + 4, reach + 4, pad_zc + pad_h / 2 + 12)",
      "result = to_mesh(hook, lo, hi, pitch=0.3)",
      "",
      "# audit: nothing but the pegs may sit behind the board face",
      "v = result.vertices",
      "behind = v[v[:, 1] < -0.05]",
      "near_peg = np.min(np.stack([np.hypot(behind[:, 0] - sx, behind[:, 2] - peg_z - rear_return / 2)",
      "                            for sx in (-hole_pitch / 2, hole_pitch / 2)]), axis=0) < rear_return",
      "assert near_peg.all(), \"material behind the board face that is not a peg\""
    ].join("\n"),
    verified: true,
  },
  {
    id: "plenum_heat_exchanger",
    title: "Dual-isolated plenum heat exchanger (squircle, gyroid core)",
    keywords: ["heat exchanger", "heat-exchanger", "exchanger", "plenum", "manifold", "two fluid", "two-fluid", "dual", "isolated", "counterflow", "coolant", "gyroid", "tpms", "radiator"],
    lesson:
      "A PRACTICAL counterflow two-fluid exchanger: tall squircle column with smoothly rounded end caps, gyroid sheet core, network-selective end seals, per-circuit plenum INLET plus labyrinth OUTLET at the far end (drill target from sampling the analytic field near the inner wall, clamped inside the open core). Every port carries a printed hose-barb stub (three sawtooth rings, sharp shoulder toward the wall) sized for 6mm-ID soft tubing — a flush hole in a wall is NOT a fastenable port. Circuits verified isolated with plugged-port void labeling.",
    code: [
      "# COUNTERFLOW plenum heat exchanger — practical two-fluid unit: each circuit",
      "# has a plenum INLET at one end and a labyrinth OUTLET at the other, and every",
      "# port carries a printed hose-barb stub (D8 stem, three sawtooth rings to",
      "# D9.5, bore D5.2) so 6mm-ID soft tubing pushes on and stays on.",
      "# hot: bottom plenum in (+X) -> up the hot labyrinth -> radial out (+X, top)",
      "# cold: top plenum in (-X) -> down the cold labyrinth -> radial out (-X, bottom)",
      "from sdf_kit import *",
      "import numpy as np",
      "A, B, H, NEXP = 21.0, 17.0, 88.0, 4.5",
      "wall = 2.0",
      "cell, t = 11.0, 1.6",
      "z1, z2 = 14.0, H - 14.0",
      "seal_h = 3.0",
      "port_r = 2.6",
      "s = (cell / (2*np.pi)) / np.sqrt(2)",
      "",
      "def sq2d(P, a, b, n):",
      "    r = (np.abs(P[:,0]/a)**n + np.abs(P[:,1]/b)**n)**(1.0/n)",
      "    return (r - 1.0) * min(a, b)",
      "",
      "def prism(P, a, b, n, z0, z1_):",
      "    return np.maximum(sq2d(P, a, b, n), np.maximum(P[:,2]-z1_, z0-P[:,2]))",
      "",
      "def soft_prism(P, a, b, n, z0, z1_, r):",
      "    # squircle prism with smoothly rounded end caps (exterior edge budget)",
      "    f = smax(sq2d(P, a, b, n), P[:,2] - z1_, r)",
      "    return smax(f, z0 - P[:,2], r)",
      "",
      "def g_raw(P):",
      "    w = 2*np.pi/cell",
      "    x, y, z = P[:,0]*w, P[:,1]*w, P[:,2]*w",
      "    return np.sin(x)*np.cos(y)+np.sin(y)*np.cos(z)+np.sin(z)*np.cos(x)",
      "",
      "def slab(P, za, zb):",
      "    return np.maximum(P[:,2]-zb, za-P[:,2])",
      "",
      "def core_body(P):",
      "    inner = prism(P, A-wall, B-wall, NEXP, wall, H-wall)",
      "    jacket = subtract(soft_prism(P, A, B, NEXP, 0, H, 2.5), inner)",
      "    g = g_raw(P)",
      "    sheet  = intersect(np.abs(g)*s - t/2, intersect(inner, slab(P, z1, z2)))",
      "    seal_b = intersect((g - 0.9)*s,  intersect(inner, slab(P, z1-seal_h, z1+1.5)))",
      "    seal_t = intersect((-g - 0.9)*s, intersect(inner, slab(P, z2-1.5, z2+seal_h)))",
      "    return union(union(jacket, sheet), union(seal_b, seal_t))",
      "",
      "# find labyrinth-void drill targets adjacent to the +X / -X inner wall",
      "def find_target(sign_g, x_side, z_center):",
      "    xs = x_side * (A - wall - 2.2)",
      "    best = None",
      "    z_lo, z_hi = max(z_center - cell/2, z1 + 2.6), min(z_center + cell/2, z2 - 2.6)",
      "    for z in np.linspace(z_lo, z_hi, 13):",
      "        for y in np.linspace(-(B - wall - 3), B - wall - 3, 21):",
      "            p = np.array([[xs, y, z]])",
      "            v = sign_g * g_raw(p)[0]",
      "            if best is None or v > best[0]:",
      "                best = (v, float(y), float(z))",
      "    return best  # (score, y, z)",
      "",
      "sh, y_hot, z_hot = find_target(+1, +1, z2 - 4.0)",
      "sc, y_cold, z_cold = find_target(-1, -1, z1 + 4.0)",
      "print(f\"drill targets: hot y={y_hot:.1f} z={z_hot:.1f} (g {sh:.2f}) | cold y={y_cold:.1f} z={z_cold:.1f} (g {sc:.2f})\")",
      "",
      "# printed hose-barb stub at each port: flare into the wall, three sawtooth",
      "# rings (gentle rise outward, sharp shoulder toward the wall = pull-off grip),",
      "# chamfered lead-in tip. Bore is cut afterwards by the extended xport.",
      "STUB_LEN = 10.0",
      "def face_x(y0):  # outer squircle surface x at this y",
      "    return A * (1.0 - (abs(y0)/B)**NEXP)**(1.0/NEXP)",
      "",
      "def barb_stub(P, x_side, y0, zc):",
      "    u = x_side * P[:,0] - face_x(y0)     # 0 at the outer face, + outward",
      "    dr = np.sqrt((P[:,1]-y0)**2 + (P[:,2]-zc)**2)",
      "    R = np.full(len(P), 4.0)",
      "    R = np.where(u < 2.0, 5.0 - 0.5*u, R)          # flare into the wall",
      "    m = (u >= 2.4) & (u <= 9.2)",
      "    saw = ((u - 2.4) % 2.6) / 2.6",
      "    R = np.where(m, 4.0 + 0.75*saw, R)             # 3 barb rings",
      "    R = np.where(u > 9.2, 3.8, R)                  # lead-in tip",
      "    return np.maximum(dr - R, np.maximum(u - STUB_LEN, -(u + 2.0)))",
      "",
      "def xport(P, x_side, y0, zc, depth_to):",
      "    u = x_side * P[:,0]",
      "    dr = np.sqrt((P[:,1]-y0)**2 + (P[:,2]-zc)**2) - port_r",
      "    return np.maximum(dr, np.maximum(u - (A + STUB_LEN + 4), depth_to - u))",
      "",
      "PORTS = [(+1, 0.0,   7.0,   A - wall - 5),     # hot_in  (bottom plenum, +X)",
      "         (-1, 0.0,   H-7.0, A - wall - 5),     # cold_in (top plenum, -X)",
      "         (+1, y_hot, z_hot, A - wall - 3.5),   # hot_out (labyrinth, +X top)",
      "         (-1, y_cold, z_cold, A - wall - 3.5)] # cold_out (labyrinth, -X bottom)",
      "",
      "def body(P, ports=True):",
      "    f = core_body(P)",
      "    for sd, y0, zc, _ in PORTS:",
      "        f = union(f, barb_stub(P, sd, y0, zc))",
      "    if ports:",
      "        for sd, y0, zc, depth in PORTS:",
      "            f = subtract(f, xport(P, sd, y0, zc, depth))",
      "    return f",
      "",
      "result = to_mesh(lambda q: body(q, ports=True), (-A-13, -B-3, -3), (A+13, B+3, H+3), pitch=0.4)",
    ].join("\n"),
    verified: true,
  },
  {
    id: "snap_lid_sensor_node",
    title: "Vented snap-lid sensor node (base + snap lid)",
    keywords: ["sensor", "snap", "snap-fit", "snap fit", "lid", "vent", "vented", "vents", "airflow", "heat-set", "heatset", "insert", "node", "iot", "enclosure", "case", "box", "two-piece", "two piece"],
    lesson:
      "Snap closure as a real, asserted mechanism: the lid's lip carries half-round snap ridges that engage window openings cut through the walls (engagement depth is computed and asserted, not eyeballed). M3 heat-set bosses use the true 4.0 mm insert bore; the sensor gets a slotted vent field through the floor. Parts sit assembled with zero interpenetration.",
    code: [
      "from build123d import *",
      "",
      "# Two-part snap-lid sensor node: vented base with M3 heat-set bosses for the",
      "# PCB, and a snap-on lid whose lip carries two snap ridges that engage window",
      "# openings in the long walls. One radius family; every fit is a named",
      "# parameter and the load-bearing ones are asserted.",
      "length, width, base_h = 70, 50, 22",
      "lid_h = 4.0",
      "wall = 2.0",
      "corner_r = 5.0",
      "fit_gap = 0.25          # lid lip to inner wall",
      "boss_d, insert_bore = 8.0, 4.0   # M3 heat-set insert: 4.0 mm bore",
      "boss_h = 6.0",
      "vent_w, vent_l, vent_pitch, n_vents = 2.0, 24.0, 6.0, 7   # floor vent slots",
      "nub_r = 1.0             # snap ridge (half-round segment)",
      "nub_len = 10.0",
      "win_w, win_h = 12.0, 3.0   # snap window in the wall",
      "lip_h = 5.0",
      "",
      "# --- numeric audit (fails loudly if a fit breaks) ---",
      "assert insert_bore == 4.0, \"M3 heat-set insert needs a 4.0 mm bore\"",
      "assert win_w >= nub_len + 1.0 and win_h >= 2 * nub_r + 0.4, \"snap window must clear the ridge\"",
      "nub_y = width / 2 - wall - fit_gap          # ridge axis sits on the lip face",
      "engagement = (nub_y + nub_r) - (width / 2 - wall)",
      "assert engagement >= 0.5, f\"snap ridge engages only {engagement:.2f} mm\"",
      "assert (n_vents - 1) * vent_pitch + vent_w < length - 2 * corner_r, \"vent field exceeds floor\"",
      "",
      "with BuildPart() as base:",
      "    Box(length, width, base_h, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "    fillet(base.edges().filter_by(Axis.Z), corner_r)",
      "    chamfer(base.edges().group_by(Axis.Z)[0], 1.0)",
      "    top = base.faces().sort_by(Axis.Z)[-1]",
      "    offset(amount=-wall, openings=top)",
      "    # M3 heat-set bosses up from the floor (PCB standoffs)",
      "    bx = length / 2 - wall - boss_d / 2 - 2.0",
      "    by = width / 2 - wall - boss_d / 2 - 2.0",
      "    with Locations((bx, by, wall), (-bx, by, wall), (bx, -by, wall), (-bx, -by, wall)):",
      "        Cylinder(boss_d / 2, boss_h, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "        Cylinder(insert_bore / 2, boss_h, align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
      "    # vented base: slot field through the floor, clear of the bosses",
      "    with BuildSketch(Plane.XY.offset(wall)):",
      "        with GridLocations(vent_pitch, 1, n_vents, 1):",
      "            SlotOverall(vent_l, vent_w, rotation=90)",
      "    extrude(amount=-wall * 2, mode=Mode.SUBTRACT)",
      "    # snap windows through both long walls, just under the rim",
      "    win_z = base_h - wall - win_h / 2 - 1.0",
      "    for sy in (-1, 1):",
      "        with BuildSketch(Plane.XZ.offset(sy * width / 2)):",
      "            with Locations((0, win_z)):",
      "                Rectangle(win_w, win_h)",
      "        extrude(amount=wall * 2, both=True, mode=Mode.SUBTRACT)",
      "",
      "with BuildPart() as lid:",
      "    with Locations((0, 0, base_h)):",
      "        Box(length, width, lid_h, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "    fillet(lid.edges().filter_by(Axis.Z), corner_r)",
      "    fillet(lid.edges().group_by(Axis.Z)[-1], 1.0)",
      "    # lip frame dropping inside the base walls",
      "    with BuildSketch(Plane.XY.offset(base_h)):",
      "        RectangleRounded(length - 2 * wall - 2 * fit_gap, width - 2 * wall - 2 * fit_gap, corner_r - wall)",
      "        RectangleRounded(length - 4 * wall - 2 * fit_gap, width - 4 * wall - 2 * fit_gap, max(1.0, corner_r - 2 * wall), mode=Mode.SUBTRACT)",
      "    extrude(amount=-lip_h)",
      "    # snap ridges: half-round segments on the lip outer faces -> the windows",
      "    win_z = base_h - wall - win_h / 2 - 1.0",
      "    for sy in (-1, 1):",
      "        with Locations((0, sy * nub_y, win_z)):",
      "            Cylinder(nub_r, nub_len, rotation=(0, 90, 0))",
      "",
      "parts = {\"base\": base.part, \"lid\": lid.part}",
    ].join("\n"),
    verified: true,
  },
  {
    id: "hinged_case_pin_bores",
    title: "Hinged case with printed pin-bore knuckles",
    keywords: ["hinge", "hinged", "hinged box", "knuckle", "pin", "pivot", "flip", "lid", "case", "box", "clamshell", "two-piece", "two part", "two-part"],
    lesson:
      "Printed hinge discipline: alternating knuckles (two outer on the base, one center on the lid) share ONE hinge axis behind the back wall, with the pin bore a named slip-fit over a 3 mm pin, barrel wall and axial knuckle gaps asserted. Webs tie each barrel into its part so nothing is loose; parts export in the closed assembled position.",
    code: [
      "from build123d import *",
      "",
      "# Two-part hinged case with printed hinge knuckles: base (2 outer knuckles)",
      "# + lid (1 center knuckle), coaxial pin bores sized for a 3 mm steel pin or",
      "# filament. Parts sit in the ASSEMBLED (closed) position; knuckle spacing,",
      "# pin clearance, and barrel standoff are named parameters with asserts.",
      "length, width, base_h = 60, 40, 20",
      "lid_t = 4.0",
      "wall = 2.0",
      "corner_r = 4.0",
      "pin_d = 3.0",
      "bore_d = 3.3            # slip fit over the pin",
      "barrel_r = 3.0",
      "standoff = 0.2          # barrel face to back wall (free rotation)",
      "knuckle_gap = 0.3       # axial gap between knuckles",
      "k_outer = 7.0           # each base knuckle length",
      "k_center = 24.0         # lid knuckle length",
      "",
      "y0 = width / 2 + barrel_r + standoff   # hinge axis (behind the back wall)",
      "z0 = base_h                            # hinge axis at the parting line",
      "",
      "# --- numeric audit ---",
      "assert bore_d - pin_d >= 0.25, \"pin bore too tight for a printed slip fit\"",
      "assert barrel_r * 2 - bore_d >= 2.0, \"hinge barrel wall under 1 mm\"",
      "lid_k_half = k_center / 2",
      "assert length / 2 - k_outer - lid_k_half >= knuckle_gap, \"knuckles interfere axially\"",
      "",
      "with BuildPart() as base:",
      "    Box(length, width, base_h, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "    fillet(base.edges().filter_by(Axis.Z), corner_r)",
      "    chamfer(base.edges().group_by(Axis.Z)[0], 1.0)",
      "    top = base.faces().sort_by(Axis.Z)[-1]",
      "    offset(amount=-wall, openings=top)",
      "    # two outer hinge knuckles + support webs bridging to the back wall",
      "    for sx in (-1, 1):",
      "        kx = sx * (length / 2 - k_outer / 2)",
      "        with Locations((kx, y0, z0)):",
      "            Cylinder(barrel_r, k_outer, rotation=(0, 90, 0))",
      "        # web: fills the standoff gap, tied into the wall below the rim",
      "        with Locations((kx, (width / 2 - 1.0 + y0) / 2, z0 - barrel_r - 1.0)):",
      "            Box(k_outer, y0 - width / 2 + 2.0, barrel_r + 1.0)",
      "    # pin bore through both knuckles",
      "    with Locations((0, y0, z0)):",
      "        Cylinder(bore_d / 2, length + 2, rotation=(0, 90, 0), mode=Mode.SUBTRACT)",
      "",
      "with BuildPart() as lid:",
      "    with Locations((0, 0, base_h)):",
      "        Box(length, width, lid_t, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "    fillet(lid.edges().filter_by(Axis.Z), corner_r)",
      "    fillet(lid.edges().group_by(Axis.Z)[-1], 1.0)",
      "    # center knuckle + web out to the hinge axis",
      "    with Locations((0, y0, z0)):",
      "        Cylinder(barrel_r, k_center, rotation=(0, 90, 0))",
      "    with Locations((0, (width / 2 - 1.0 + y0) / 2, z0 + (lid_t + barrel_r) / 2 - barrel_r / 2)):",
      "        Box(k_center, y0 - width / 2 + 2.0, lid_t)",
      "    with Locations((0, y0, z0)):",
      "        Cylinder(bore_d / 2, k_center + 2, rotation=(0, 90, 0), mode=Mode.SUBTRACT)",
      "",
      "parts = {\"base\": base.part, \"lid\": lid.part}",
    ].join("\n"),
    verified: true,
  },
  {
    id: "strain_relief_clamshell",
    title: "Cable strain-relief clamshell (screw-clamped halves)",
    keywords: ["strain relief", "strain-relief", "cable", "cord", "wire", "clamp", "clamshell", "gland", "grommet", "grip", "two-piece", "two piece", "halves"],
    lesson:
      "Mating halves from ONE parametric function (no copy-paste drift): split through the cable axis, annular grip ribs sized by a rib-bite parameter, flared entries so the cord has no sharp bend point, M3 clearance + counterbore above vs self-tap pilots below, and diagonal registration pins with an asserted printed clearance.",
    code: [
      "from build123d import *",
      "",
      "# Two-piece cable strain-relief clamshell: halves split through the cable",
      "# axis, annular grip ribs biting the jacket, flared entries, two M3 screws",
      "# (clearance + counterbore above, self-tap pilot below), and diagonal",
      "# registration pins with an asserted printed clearance. ONE parametric",
      "# function builds both halves \u2014 no copy-paste drift between mating parts.",
      "block_l, block_w, half_h = 36, 24, 8",
      "corner_r = 4.0",
      "cable_d = 8.0            # cable jacket OD",
      "bore_r = cable_d / 2",
      "rib_bite = 0.6           # ribs close the bore by this much per side",
      "rib_t, rib_pitch, n_ribs = 1.2, 6.0, 3",
      "flare_r, flare_l = 5.5, 5.0",
      "screw_clear_r, screw_pilot_r = 1.7, 1.25   # M3",
      "cbore_r, cbore_h = 3.25, 3.0",
      "pin_r, pin_h, pin_clear = 1.5, 1.6, 0.15",
      "screw_y = 7.5",
      "pin_x, pin_y = 13.0, 7.0",
      "",
      "# --- numeric audit ---",
      "assert screw_pilot_r < 1.5 < screw_clear_r, \"M3 pilot/clearance out of order\"",
      "assert bore_r - rib_bite >= 2.5, \"ribs close the bore below a usable cable core\"",
      "assert screw_y - screw_clear_r > bore_r + 0.8, \"screw bores break into the cable bore\"",
      "assert screw_y + cbore_r < block_w / 2, \"counterbores break out of the block\"",
      "assert pin_clear >= 0.1, \"registration pins need a printed clearance\"",
      "",
      "def clamshell_half(top: bool):",
      "    with BuildPart() as half:",
      "        Box(block_l, block_w, half_h,",
      "            align=(Align.CENTER, Align.CENTER, Align.MIN if top else Align.MAX))",
      "        fillet(half.edges().filter_by(Axis.Z), corner_r)",
      "        fillet(half.edges().group_by(Axis.Z)[-1 if top else 0], 2.0)",
      "        # main cable bore along X",
      "        Cylinder(bore_r, block_l + 2, rotation=(0, 90, 0), mode=Mode.SUBTRACT)",
      "        # grip ribs: washers fused to the bore wall, clipped to this half",
      "        with Locations(*[((i - (n_ribs - 1) / 2) * rib_pitch, 0, 0) for i in range(n_ribs)]):",
      "            Cylinder(bore_r + 0.2, rib_t, rotation=(0, 90, 0))",
      "        Box(block_l, block_w, half_h,",
      "            align=(Align.CENTER, Align.CENTER, Align.MIN if top else Align.MAX),",
      "            mode=Mode.INTERSECT)",
      "        # open the rib ID (what actually grips the jacket)",
      "        Cylinder(bore_r - rib_bite, block_l + 2, rotation=(0, 90, 0), mode=Mode.SUBTRACT)",
      "        # flared entries (strain relief: no sharp bend point at the mouth)",
      "        for sx in (-1, 1):",
      "            with Locations((sx * block_l / 2, 0, 0)):",
      "                Cone(flare_r, bore_r - rib_bite, flare_l,",
      "                     rotation=(0, sx * -90, 0), mode=Mode.SUBTRACT)",
      "        if top:",
      "            # M3 clearance + counterbore from above",
      "            with Locations((0, screw_y, half_h), (0, -screw_y, half_h)):",
      "                CounterBoreHole(screw_clear_r, cbore_r, cbore_h, depth=half_h)",
      "            # registration recesses (pin + printed clearance)",
      "            with Locations((pin_x, pin_y, 0), (-pin_x, -pin_y, 0)):",
      "                Cylinder(pin_r + pin_clear, pin_h + 0.4,",
      "                         align=(Align.CENTER, Align.CENTER, Align.MIN), mode=Mode.SUBTRACT)",
      "        else:",
      "            # self-tap pilots down into the bottom half",
      "            with Locations((0, screw_y, 0), (0, -screw_y, 0)):",
      "                Cylinder(screw_pilot_r, 6.0,",
      "                         align=(Align.CENTER, Align.CENTER, Align.MAX), mode=Mode.SUBTRACT)",
      "            # diagonal registration pins on the mating face",
      "            with Locations((pin_x, pin_y, 0), (-pin_x, -pin_y, 0)):",
      "                Cylinder(pin_r, pin_h, align=(Align.CENTER, Align.CENTER, Align.MIN))",
      "    return half.part",
      "",
      "parts = {\"clamp_bottom\": clamshell_half(False), \"clamp_top\": clamshell_half(True)}",
    ].join("\n"),
    verified: true,
  },
  {
    id: "oled_window_front_plate_box",
    title: "OLED display box (body + bezel face plate)",
    keywords: ["display", "oled", "ssd1306", "screen", "window", "bezel", "aperture", "face plate", "faceplate", "front plate", "front-plate", "gauge", "monitor", "readout"],
    lesson:
      "Display bezel from TRUE module datums: the window is asserted smaller than the SSD1306 glass but larger than its active area, and the M2 posts sit on the module's real hole grid with the pilot stopped short of the face. The cavity is built as an explicit inner offset (offset(openings=side_face) silently no-ops once corner fillets bound the face) and the plate's lip seats in a rebated front aperture.",
    code: [
      "from build123d import *",
      "",
      "# Desk display box for a 0.96\" SSD1306 OLED breakout: body + bezel face plate.",
      "# The window is sized from the module's true datums (smaller than the glass,",
      "# larger than the active area); the module screws to the plate's back on four",
      "# M2 self-tap posts; the plate's lip seats in a rebated front aperture.",
      "body_w, body_d, body_h = 42, 18, 38",
      "plate_t = 2.5",
      "wall = 2.0",
      "corner_r = 4.0",
      "fit_gap = 0.25",
      "lip_d = 3.0",
      "# --- SSD1306 0.96\" breakout datums ---",
      "oled_glass_w, oled_glass_h = 26.7, 19.3    # glass outline",
      "oled_active_w, oled_active_h = 21.7, 10.9  # emitting area",
      "hole_dx, hole_dz = 23.5, 23.8              # M2 mounting grid",
      "win_w, win_h = 23.0, 12.0                  # bezel aperture",
      "win_z = 21.0                               # window center height (eye line)",
      "post_r, pilot_r, post_l = 2.0, 0.8, 5.0    # M2 self-tap: pilot D1.6",
      "cable_d = 8.0",
      "ap_w = ap_h = 34.0                         # front aperture (rebate the lip seats in)",
      "ap_z = 2.0 + ap_h / 2                      # aperture spans floor to ceiling",
      "",
      "# --- numeric audit (window must land ON the module) ---",
      "assert win_w < oled_glass_w and win_h < oled_glass_h, \"aperture exceeds the glass \u2014 module falls through\"",
      "assert win_w > oled_active_w + 0.8 and win_h > oled_active_h + 0.8, \"aperture crops the active area\"",
      "assert hole_dz / 2 - post_r > win_h / 2, \"posts intrude into the window\"",
      "assert win_z + hole_dz / 2 + post_r < 2.0 + ap_h, \"top posts hit the cavity ceiling\"",
      "assert ap_w / 2 <= body_w / 2 - corner_r, \"aperture cuts into the corner fillets\"",
      "",
      "with BuildPart() as body:",
      "    Box(body_w, body_d, body_h, align=(Align.CENTER, Align.MIN, Align.MIN))",
      "    fillet(body.edges().filter_by(Axis.Z), corner_r)",
      "    chamfer(body.edges().group_by(Axis.Z)[0], 1.0)",
      "    # NOTE: offset(openings=front) silently no-ops once the front face is",
      "    # bounded by the corner-fillet arcs, so the cavity is constructed",
      "    # explicitly as the true inner offset (plan radius = corner_r - wall,",
      "    # every wall exactly `wall` thick). Interior corners stay crisp per the",
      "    # edge budget.",
      "    with BuildSketch(Plane.XY.offset(wall)):",
      "        with Locations((0, body_d / 2)):",
      "            RectangleRounded(body_w - 2 * wall, body_d - 2 * wall, corner_r - wall)",
      "    extrude(amount=body_h - 2 * wall, mode=Mode.SUBTRACT)",
      "    # rebated front aperture the face plate's lip seats into",
      "    with BuildSketch(Plane.XZ):",
      "        with Locations((0, ap_z)):",
      "            RectangleRounded(ap_w, ap_h, corner_r - wall)",
      "    extrude(amount=-(wall + 1.0), mode=Mode.SUBTRACT)",
      "    # top edge break (kept < wall)",
      "    fillet(body.edges().group_by(Axis.Z)[-1], 1.5)",
      "    # cable exit low in the back wall",
      "    with Locations((0, body_d, 10)):",
      "        Cylinder(cable_d / 2, wall * 3, rotation=(90, 0, 0), mode=Mode.SUBTRACT)",
      "",
      "with BuildPart() as plate:",
      "    with Locations((0, -plate_t, 0)):",
      "        Box(body_w, plate_t, body_h, align=(Align.CENTER, Align.MIN, Align.MIN))",
      "    # outline follows the body silhouette: soft top corners, chamfered base",
      "    fillet(plate.edges().filter_by(Axis.Y).group_by(Axis.Z)[-1], corner_r)",
      "    chamfer(plate.edges().group_by(Axis.Z)[0], 1.0)",
      "    # lip frame seating in the aperture rebate (friction fit). Plane.XZ's",
      "    # normal points -Y, so extrude NEGATIVE to run the lip +Y into the body.",
      "    with BuildSketch(Plane.XZ):",
      "        with Locations((0, ap_z)):",
      "            RectangleRounded(ap_w - 2 * fit_gap, ap_h - 2 * fit_gap, corner_r - wall)",
      "            RectangleRounded(ap_w - 2 * fit_gap - 2 * wall, ap_h - 2 * fit_gap - 2 * wall, max(1.0, corner_r - 2 * wall), mode=Mode.SUBTRACT)",
      "    extrude(amount=-lip_d)",
      "    # display window with a beveled aperture (the bezel move)",
      "    with Locations((0, 0, win_z)):",
      "        Box(win_w, plate_t * 3, win_h, mode=Mode.SUBTRACT)",
      "    win_edges = plate.edges().filter_by(",
      "        lambda e: abs(e.center().Y + plate_t) < 0.05",
      "        and abs(e.center().X) < win_w / 2 + 1",
      "        and abs(e.center().Z - win_z) < win_h / 2 + 1",
      "    )",
      "    chamfer(win_edges, 1.2)",
      "    # M2 posts on the module's true hole grid, pilots stop 1.2mm from the face",
      "    with BuildSketch(Plane.XZ):",
      "        with Locations(*[(sx * hole_dx / 2, win_z + sz * hole_dz / 2) for sx in (-1, 1) for sz in (-1, 1)]):",
      "            Circle(post_r)",
      "    extrude(amount=-post_l)",
      "    with BuildSketch(Plane.XZ.offset(plate_t - 1.2)):",
      "        with Locations(*[(sx * hole_dx / 2, win_z + sz * hole_dz / 2) for sx in (-1, 1) for sz in (-1, 1)]):",
      "            Circle(pilot_r)",
      "    extrude(amount=-(post_l + plate_t - 1.2), mode=Mode.SUBTRACT)",
      "",
      "parts = {\"body\": body.part, \"face_plate\": plate.part}",
    ].join("\n"),
    verified: true,
  },
  {
    id: "wall_mount_keyhole_bin",
    title: "Wall-mount holder with keyhole mounts",
    keywords: ["wall mount", "wall-mount", "wall", "keyhole", "hanger", "hanging", "hang", "holder", "bin", "bracket", "caddy", "remote", "mount"],
    lesson:
      "Keyhole mounting as checked geometry: the head hole passes an M4 pan head, the rising slot passes only the shank (both asserted), and the keyholes cut through internal reinforcement pads so 2 mm walls still capture the head. Open-top shelled bin with a rim break after the shell and a finger scoop dished into the front edge.",
    code: [
      "from build123d import *",
      "",
      "# Wall-mount holder: an open-top bin with a finger scoop and two keyhole",
      "# mounts on reinforced internal pads. Keyhole datums are named + asserted:",
      "# the head hole passes a #8/M4 pan head, the slot passes only the shank, so",
      "# the part locks when it slides down onto the screws.",
      "bin_w, bin_d, bin_h = 60, 25, 40",
      "wall = 2.0",
      "corner_r = 6.0",
      "scoop_r = 15.0",
      "head_d, shank_d = 7.0, 4.0     # M4 / #8 pan head screw",
      "hole_d, slot_w = 8.0, 4.6      # keyhole: head hole + shank slot",
      "slot_rise = 8.0",
      "pad_w, pad_h, pad_t = 14.0, 20.0, 2.5   # internal reinforcement pads",
      "key_x, key_z = 16.0, 24.0      # keyhole centers (two, level)",
      "pad_cz = key_z + slot_rise / 2  # pad centered on the full keyhole travel",
      "",
      "# --- numeric audit ---",
      "assert hole_d > head_d + 0.8, \"head hole must pass the screw head\"",
      "assert shank_d + 0.4 <= slot_w < head_d, \"slot must pass the shank but capture the head\"",
      "assert key_z + slot_rise + slot_w / 2 < pad_cz + pad_h / 2, \"slot escapes the pad\"",
      "assert key_z - hole_d / 2 > pad_cz - pad_h / 2, \"head hole escapes the pad\"",
      "assert pad_w > hole_d + 4.0, \"pad too narrow around the head hole\"",
      "",
      "with BuildPart() as part:",
      "    Box(bin_w, bin_d, bin_h, align=(Align.CENTER, Align.MIN, Align.MIN))",
      "    fillet(part.edges().filter_by(Axis.Z), corner_r)",
      "    chamfer(part.edges().group_by(Axis.Z)[0], 1.0)",
      "    top = part.faces().sort_by(Axis.Z)[-1]",
      "    offset(amount=-wall, openings=top)",
      "    fillet(part.edges().group_by(Axis.Z)[-1], 0.8)   # rim break after shell",
      "    # finger scoop dished into the front wall's top edge",
      "    with Locations((0, 0, bin_h)):",
      "        Cylinder(scoop_r, wall * 3, rotation=(90, 0, 0), mode=Mode.SUBTRACT)",
      "    # internal reinforcement pads on the back wall (keyholes need meat)",
      "    with Locations((key_x, bin_d - wall, pad_cz), (-key_x, bin_d - wall, pad_cz)):",
      "        Box(pad_w, pad_t, pad_h, align=(Align.CENTER, Align.MAX, Align.CENTER))",
      "    # keyholes cut through wall + pad from the back face",
      "    for sx in (-1, 1):",
      "        with BuildSketch(Plane.XZ.offset(-(bin_d + 1))):",
      "            with Locations((sx * key_x, key_z)):",
      "                Circle(hole_d / 2)",
      "            with Locations((sx * key_x, key_z + slot_rise / 2)):",
      "                Rectangle(slot_w, slot_rise)",
      "            with Locations((sx * key_x, key_z + slot_rise)):",
      "                Circle(slot_w / 2)",
      "        extrude(amount=wall + pad_t + 2, mode=Mode.SUBTRACT)",
      "",
      "result = part.part",
    ].join("\n"),
    verified: true,
  },
  {
    id: "dual_fluid_exchanger",
    title: "Dual-fluid gyroid heat-exchanger block",
    keywords: ["heat exchanger", "exchanger", "gyroid", "tpms", "dual fluid", "two fluid", "dual-fluid", "coolant", "intercooler", "manifold", "hot", "cold", "lattice", "counterflow", "crossflow"],
    lesson:
      "A two-fluid TPMS core is ONE sheet field, never two overlapping lattices: the gyroid sheet separates two congruent labyrinths that share every wall (max exchange area per volume), and exchanger_core seals the OTHER fluid's labyrinth at each plenum face — a plain cut exposes both labyrinths on every face, so capping is what makes manifolds possible. Asymmetric port bores (port_r dict) and lofted external hose barbs (hose dict) are generator parameters, NOT hand-rolled geometry — hand-rolled manifolds have bored leak paths through cores via sign errors. Declaring fluid_ports + fluid_plugs makes the sidecar prove circuit isolation at voxel resolution; wall and pitch are named parameters with the printability contract (pitch <= wall/3) asserted, not implied.",
    code: [
      "from sdf_kit import to_mesh",
      "from exchanger import exchanger_core",
      "",
      "# Dual-fluid gyroid heat exchanger: hot fluid A crosses cold fluid B",
      "# through two isolated labyrinths sharing every wall of one TPMS sheet.",
      "# Sized to run inside the sidecar budget — scale `core` up for a real",
      "# duty, keeping pitch <= wall/3 and the grid under the cell budget.",
      "core = (30, 30, 24)   # gyroid core box, mm",
      "cell = 8.0            # lattice period; 6-12mm de-powders reliably",
      "wall = 1.2            # separator sheet; >= 1.0mm for polymer",
      "pitch = 0.4           # mesh resolution",
      "",
      "# Printability contract: coarser than wall/3 punches false pinholes",
      "# through the wall at meshing time (epsilon for float division).",
      "assert pitch <= wall / 3 + 1e-9, \"pitch must be <= wall/3\"",
      "",
      "# hose: hood-loft manifolds built BY the generator — each hooded port",
      "# opens its ENTIRE plenum window (the header collects the whole core",
      "# face) and morphs rect-to-round down to the hose bore with a cubic-",
      "# eased (Bezier-swept) profile, then a ringed barb run for the hose to",
      "# clamp onto. Plugs and meshing bounds update automatically. Values",
      "# are hose INNER diameters in mm; asymmetric inlet/outlet is fine.",
      "field, ports, plugs, bounds = exchanger_core(",
      "    core, cell=cell, wall=wall, kind=\"gyroid\", flow=\"cross\",",
      "    hose={\"a_in\": 12.0, \"a_out\": 10.0, \"b\": 6.0})",
      "result = to_mesh(field, *bounds, pitch=pitch)",
      "",
      "# The sidecar verifies the two circuits are isolated (a_in/a_out vs",
      "# b_in/b_out) with the port bores virtually plugged — open ports would",
      "# otherwise read as a leak through the outside air. min_feature keeps",
      "# the probe finer than the wall on large cores (a coarser probe would",
      "# alias sound walls into phantom leaks).",
      "fluid_ports = ports",
      "fluid_plugs = plugs",
      "fluid_min_feature = wall",
    ].join("\n"),
    verified: true,
  },
];

/**
 * The live pool: hand-authored entries + farm-promoted entries
 * (lib/cad/knowledge/exemplars-farmed.ts, human-approved via
 * scripts/exemplar-farm/promote.ts). A farmed id never shadows an authored
 * one — promote.ts refuses collisions with the authored set.
 */
export const CAD_EXEMPLARS: CadExemplar[] = [
  ...AUTHORED_EXEMPLARS,
  ...FARMED_EXEMPLARS,
];

/** Score an exemplar against a prompt by keyword hits. */
function score(prompt: string, ex: CadExemplar): number {
  const p = prompt.toLowerCase();
  return ex.keywords.reduce((s, k) => (p.includes(k) ? s + 1 : s), 0);
}

/**
 * Pick the best-matching VERIFIED exemplar(s) for a prompt. Unverified
 * exemplars are never returned, so an unproven part can't reach the model.
 * `pool` is injectable for tests.
 */
export function selectExemplars(
  prompt: string,
  opts: { limit?: number; pool?: CadExemplar[] } = {}
): CadExemplar[] {
  const limit = opts.limit ?? 1;
  const pool = (opts.pool ?? CAD_EXEMPLARS).filter((e) => e.verified);
  return pool
    .map((e) => ({ e, s: score(prompt, e) }))
    .filter(({ s }) => s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, limit)
    .map(({ e }) => e);
}

/**
 * Which engine an exemplar's code targets, DERIVED from the code rather than
 * hand-tagged. A tag would be one more list to keep in sync, and this repo
 * has already been bitten by exactly that (the Dockerfile's hand-kept COPY
 * list shipped an image missing three modules). An exemplar that imports
 * sdf_kit or meshes a field IS an implicit exemplar; nothing else is.
 */
export function exemplarEngine(ex: CadExemplar): CadEngineId {
  // The real test is what `result` ends up being: a trimesh (implicit) or a
  // B-rep solid. sdf_kit is the common route, but MESH MODE exemplars reach
  // the same place with raw numpy + skimage.measure.marching_cubes and no
  // sdf_kit import at all — gyroid_tpms_core is one, and a narrower check
  // misfiled it as build123d, which is how a build123d-only prompt came to be
  // offered a marching-cubes exemplar.
  return /from sdf_kit import|\bto_mesh\(|marching_cubes|trimesh\.Trimesh/.test(
    ex.code
  )
    ? "sdf"
    : "brep";
}

/**
 * Exemplar pool for an engine, to pass as `selectExemplars({ pool })`.
 *
 * NOTE the asymmetry, which is deliberate: "brep" returns the pool UNCHANGED,
 * including the implicit exemplars. The build123d prompt still carries its
 * own SDF section for organic prompts, so filtering them out would change
 * that engine's behaviour — and the engine registry's whole safety claim is
 * that the B-rep path is untouched. The implicit engine, which cannot run
 * build123d at all, gets only implicit exemplars.
 */
export function exemplarPoolFor(
  engine: CadEngineId,
  opts: { prompt?: string; pool?: CadExemplar[] } = {}
): CadExemplar[] {
  const pool = opts.pool ?? CAD_EXEMPLARS;
  if (engine === "sdf") return pool.filter((e) => exemplarEngine(e) === "sdf");
  // B-rep: only offer implicit exemplars when the assembled prompt actually
  // DESCRIBED the implicit vocabulary. The prompt's section gate and the
  // exemplar keyword scoring are independent, so they can disagree — and did:
  // "a pair of meshing spur gears" gets the core-only build123d prompt and
  // still scored the gyroid mesh-mode exemplar highest, teaching a dialect
  // the system prompt never authorized. With no prompt supplied the pool is
  // unchanged, so existing callers keep today's behaviour.
  if (opts.prompt === undefined) return pool;
  return selectSystemPromptSections(opts.prompt).sdf
    ? pool
    : pool.filter((e) => exemplarEngine(e) === "brep");
}

/**
 * Resolve exemplar ids the plan/brief step chose from the catalog (retrieval
 * v2, docs/text-to-cad/07 §C). Validated against the pool + verified-only +
 * capped at 2, so a hallucinated or unverified id can never inject code.
 * `pool` is injectable for tests.
 */
export function selectExemplarsByIds(
  ids: string[],
  opts: { pool?: CadExemplar[] } = {}
): CadExemplar[] {
  const pool = (opts.pool ?? CAD_EXEMPLARS).filter((e) => e.verified);
  const out: CadExemplar[] = [];
  for (const id of ids) {
    const ex = pool.find((e) => e.id === id);
    if (ex && !out.includes(ex)) out.push(ex);
    if (out.length >= 2) break;
  }
  return out;
}

/**
 * Catalog listing (id + title + keywords + lesson — NOT code) shown to the
 * plan/brief steps so the model picks its own style reference instead of
 * relying on brittle keyword overlap.
 */
export function formatExemplarCatalog(pool: CadExemplar[] = CAD_EXEMPLARS): string {
  const rows = pool.filter((e) => e.verified);
  if (rows.length === 0) return "";
  const lines = rows.map(
    (e) => `- ${e.id} — ${e.title} (${e.keywords.join(", ")}): ${e.lesson}`
  );
  return ["Exemplar catalog (style references available to the code generator):", ...lines].join(
    "\n"
  );
}

export function formatExemplars(rows: CadExemplar[]): string {
  if (rows.length === 0) return "";
  const blocks = rows.map(
    (e) =>
      `Example — ${e.title} (${e.lesson}):\n\`\`\`python\n${e.code}\n\`\`\``
  );
  return [
    "Reference example(s) of well-designed parametric build123d (match this level of edge treatment and parametric structure; do not copy verbatim):",
    ...blocks,
  ].join("\n\n");
}
