import "server-only";

import { getObjectBytes, objectExists, putObject } from "@/lib/storage";
import { logError } from "@/lib/logger";
import { buildLowDetailModel, isPreviewFormat } from "@/lib/mesh/decimate";

/**
 * Low-detail model previews for paid listings.
 *
 * A paid file (files.price > 0) never hands its full-resolution mesh to a
 * viewer who isn't entitled to it (lib/entitlement.ts `ownsLoadedFile`).
 * They get a vertex-clustered copy instead (lib/mesh/decimate.ts):
 * recognizable in the 3D viewer, too coarse to be worth printing.
 *
 * The copy is generated lazily on the first non-entitled request and
 * cached in R2 at a DETERMINISTIC key derived from the asset id. Assets
 * are immutable (a new version is a new fileAssets row), so the key never
 * goes stale and needs no DB column. Bump PREVIEW_KEY_VERSION whenever
 * the decimation changes (PREVIEW_GRID_CELLS or the algorithm), or every
 * cached preview keeps the old output.
 *
 * The preview is ALWAYS in the original's format: the viewer chooses its
 * three.js loader client-side from fileAssets.format, so a 3MF listing
 * must get a 3MF preview. STEP/AMF have no browser loader (the viewer
 * shows a placeholder) and no preview — callers refuse the bytes.
 */

export const PREVIEW_KEY_VERSION = 1;
export const PREVIEW_PREFIX = "previews/";

const PREVIEW_MIME: Record<string, string> = {
  stl: "model/stl",
  obj: "text/plain",
  "3mf": "model/3mf",
};

export function previewStorageKey(fileAssetId: string, format: string): string {
  return `${PREVIEW_PREFIX}${fileAssetId}.v${PREVIEW_KEY_VERSION}.${format}`;
}

/**
 * Asset id a preview key was generated for, or null when the key isn't
 * one of ours. Used by the orphan sweep to drop previews of deleted assets.
 */
export function assetIdFromPreviewKey(key: string): string | null {
  if (!key.startsWith(PREVIEW_PREFIX)) return null;
  const m = /^([^/.]+)\.v\d+\.[a-z0-9]+$/.exec(key.slice(PREVIEW_PREFIX.length));
  return m ? m[1] : null;
}

/**
 * Must this viewer get the low-detail copy? Only for a paid listing they
 * aren't entitled to. Free files are entitled for everyone by definition
 * (ownsLoadedFile returns true at price 0), so `entitled` is only worth
 * computing when price > 0.
 */
export function needsLowDetailPreview(args: {
  price: number | null | undefined;
  entitled: boolean;
}): boolean {
  return (args.price ?? 0) > 0 && !args.entitled;
}

/**
 * The low-detail bytes for an asset, generating and caching them on first
 * use. Returns null when there is no preview to give (STEP/AMF, or a file
 * that doesn't parse) — callers must refuse the request then, never fall
 * back to the original.
 *
 * Two concurrent first requests both generate and both PUT; the output is
 * deterministic for the same input, so the race is harmless. A failed
 * cache write is logged and the generated bytes are still served.
 */
export async function getPreviewBytes(asset: {
  id: string;
  storageKey: string;
  format: string;
}): Promise<Uint8Array | null> {
  if (!isPreviewFormat(asset.format)) return null;
  const key = previewStorageKey(asset.id, asset.format);

  const cached = await objectExists(key);
  if (cached.exists) return getObjectBytes(key);

  const original = await getObjectBytes(asset.storageKey);
  const built = buildLowDetailModel(original, asset.format);
  if (!built) return null;

  try {
    await putObject(key, built.bytes, PREVIEW_MIME[asset.format]);
  } catch (err) {
    logError("files.model-preview.cache", err);
  }
  return built.bytes;
}
